<?php
namespace Tests\Unit;
use CodeIgniter\Test\CIUnitTestCase;
final class HrFinalRankReviewPhaseOTest extends CIUnitTestCase
{
 private function source(string $p):string{return file_get_contents(ROOTPATH.$p);}
 public function testHrAcceptAndAdjustmentPreserveEvaluatorRecommendation():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString("\$action=\$adjusted?'adjusted':'accepted'",$s);self::assertStringContainsString("'evaluator_recommended_rank_code'=>\$d['confirmed_rank_code']",$s);self::assertStringContainsString("'hr_final_rank_code'=>\$rankCode",$s);}
 public function testAdjustmentRequiresReasonAndSystemValidOption():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('INVALID_HR_FINAL_RANK_OPTION',$s);self::assertStringContainsString('HR_ADJUSTMENT_JUSTIFICATION_REQUIRED',$s);self::assertStringContainsString("array_column(\$d['valid_rank_options'],'rank_code')",$s);}
 public function testReturnRequiresReasonAndIsNotPortfolioRevision():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('RECONSIDERATION_REASON_REQUIRED',$s);self::assertStringContainsString("'portfolio_revision'=>false",$s);}
 public function testReconsiderationClonesEvaluationAndItemsAsNewVersion():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString("\$new['version_number']=(int)\$old['version_number']+1",$s);self::assertStringContainsString("\$new['previous_version_id']=\$old['id']",$s);self::assertStringContainsString("table('personnel_evaluation_items')->insert(\$item)",$s);self::assertStringContainsString("'fresh_recommended_rank_required'=>true",$s);}
 public function testOldRecommendationRemainsTraceableAndNewVersionDoesNotInheritIt():void{$m=$this->source('app/Database/Migrations/2026-09-15-000010_CreateHrFinalRankReviews.php');self::assertStringContainsString('recommended_rank_decision_id',$m);$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringNotContainsString("personnel_recommended_rank_decisions')->insert",$s);}
 public function testFreshnessLatestVersionAndHrAuthorizationAreRequired():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('assertFreshConfirmedDecision',$s);self::assertStringContainsString('EVALUATION_VERSION_SUPERSEDED',$s);self::assertStringContainsString('HR_AUTHORITY_REQUIRED',$s);self::assertStringContainsString('actorMayAct',$s);}
 public function testRecommendationCannotBeReviewedTwice():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('assertUnreviewed($recommendedId)',$s);self::assertStringContainsString('HR_FINAL_RANK_REVIEW_ALREADY_RECORDED',$s);}
 public function testSuccessfulFinalizationEndsReadyForPrintingWithoutPresentRankMutation():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString("'status'=>'finalized_ready_for_printing'",$s);self::assertStringContainsString('Finalized — Ready for Printing',$s);self::assertStringNotContainsString('current_rank_title',$s);}
 public function testLegacyFinalizeCannotBypassPhaseO():void{$c=$this->source('app/Controllers/Api/HREvaluationController.php');self::assertStringContainsString('HR_FINAL_RANK_REVIEW_REQUIRED',$c);}
}
