<?php
namespace Tests\Unit;
use CodeIgniter\Test\CIUnitTestCase;
final class HrFinalRankReviewPhaseOTest extends CIUnitTestCase
{
 private function source(string $p):string{return file_get_contents(ROOTPATH.$p);}
 public function testHrAcceptAndAdjustmentPreserveEvaluatorRecommendation():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString("\$action=\$adjusted?'adjusted':'accepted'",$s);self::assertStringContainsString("'evaluator_recommended_rank_code'=>\$d['confirmed_rank_code']",$s);self::assertStringContainsString("'hr_final_rank_code'=>\$rankCode",$s);}
 public function testAdjustmentRequiresReasonAndSystemValidOption():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('INVALID_HR_FINAL_RANK_OPTION',$s);self::assertStringContainsString('HR_ADJUSTMENT_JUSTIFICATION_REQUIRED',$s);self::assertStringContainsString("array_column(\$d['valid_rank_options'],'rank_code')",$s);}
 public function testReturnRequiresReasonAndIsNotPortfolioRevision():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('RECONSIDERATION_REASON_REQUIRED',$s);self::assertStringContainsString("'portfolio_revision'=>false",$s);}
 public function testReconsiderationClonesEvaluationAndItemsAsNewVersion():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString("\$new['version_number']=(int)\$old['version_number']+1",$s);self::assertStringContainsString("\$new['previous_version_id']=\$old['id']",$s);self::assertStringContainsString("table('personnel_evaluation_items')->insert(\$item)",$s);self::assertStringContainsString("'fresh_recommended_rank_required'=>true",$s);}
 public function testReconsiderationCloneUsesOnlyPersistedEvaluationColumns():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');$method=strstr(strstr($s,'public function beginReconsideration('),'public function context',true);self::assertStringNotContainsString("\$new['ready_at']",$method);}
 public function testOldRecommendationRemainsTraceableAndNewVersionDoesNotInheritIt():void{$m=$this->source('app/Database/Migrations/2026-09-15-000010_CreateHrFinalRankReviews.php');self::assertStringContainsString('recommended_rank_decision_id',$m);$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringNotContainsString("personnel_recommended_rank_decisions')->insert",$s);}
 public function testFreshnessLatestVersionAndHrAuthorizationAreRequired():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('assertFreshConfirmedDecision',$s);self::assertStringContainsString('EVALUATION_VERSION_SUPERSEDED',$s);self::assertStringContainsString('HR_AUTHORITY_REQUIRED',$s);self::assertStringContainsString('actorMayAct',$s);}
 public function testRecommendationCannotBeReviewedTwice():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('assertUnreviewed($recommendedId)',$s);self::assertStringContainsString('HR_FINAL_RANK_REVIEW_ALREADY_RECORDED',$s);}
 public function testSuccessfulFinalizationEndsReadyForPrintingWithoutPresentRankMutation():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');$finalize=strstr(strstr($s,'public function finalize('),'public function returnForReconsideration',true);self::assertStringContainsString("'status'=>'finalized_ready_for_printing'",$finalize);self::assertStringContainsString('Finalized — Ready for Printing',$finalize);self::assertStringNotContainsString('current_rank_title',$finalize);}
 public function testSuccessfulFinalizationCreatesTheExistingCompletedResultReport():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');$finalize=strstr(strstr($s,'public function finalize('),'public function returnForReconsideration',true);self::assertStringContainsString('ensureCompletedResultReport',$finalize);self::assertStringContainsString("table('personnel_evaluation_reports')->insert",$s);self::assertStringContainsString('PersonnelEvaluationSummaryService',$s);}
 public function testClassificationAwareBoundaryKeepsFacultyBoundToPhaseOWithoutBlockingReads():void{$c=$this->source('app/Controllers/Api/HREvaluationController.php');$get=strstr(strstr($c,'public function get(string $id)'), 'public function start', true);$finalize=strstr($c,'public function finalizeEvaluation(string $id)');$s=$this->source('app/Services/ClassificationAwarePersonnelFinalizationService.php');self::assertStringNotContainsString('HR_FINAL_RANK_REVIEW_REQUIRED',$get);self::assertStringContainsString('finalizationService->finalize',$finalize);self::assertStringContainsString("if (\$group === self::FACULTY)",$s);self::assertStringContainsString("throw new RuntimeException('HR_FINAL_RANK_REVIEW_REQUIRED')",$s);}
 public function testProductionContextIsFacultyOnlyVersionBoundAndRoleScoped():void{$s=$this->source('app/Services/HrFinalRankReviewService.php');self::assertStringContainsString('FACULTY_PHASE_O_NOT_APPLICABLE',$s);self::assertStringContainsString('EVALUATION_VERSION_SUPERSEDED',$s);self::assertStringContainsString('PHASE_O_CONTEXT_ACCESS_DENIED',$s);self::assertStringContainsString("'actor_mode'=>\$isHr?'hr':'reviewer'",$s);$r=$this->source('app/Config/Routes.php');self::assertStringContainsString("reviewer/evaluations/(:segment)/phase-o",$r);}
 public function testHrQueueCanSeeDeanEndorsedCases():void{$c=$this->source('app/Controllers/Api/HREvaluationController.php');$list=strstr(strstr($c,'public function list()'),'public function get(string $id)',true);self::assertStringContainsString('if (! $this->isHrAdmin($actor))',$list);self::assertStringContainsString("where('pe.evaluator_profile_id', \$actor['profile']['id'])",$list);}
}
