<?php
namespace Tests\Unit;
use PHPUnit\Framework\TestCase;
class OfficialPrintableEvaluationSummaryPhasePTest extends TestCase
{
 private function source(string $p):string{return file_get_contents(ROOTPATH.$p);}
 public function testOnlyFinalizedPhaseOReviewCanGenerate():void{$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString("'finalized_ready_for_printing'",$s);self::assertStringContainsString('EVALUATION_NOT_FINALIZED_READY_FOR_PRINTING',$s);}
 public function testFinalConfirmedRanksArePrintedWithoutInternalNotes():void{$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString("\$applied['confirmed_rank_code']",$s);self::assertStringContainsString("\$review['hr_final_rank_code']",$s);$h=$this->source('app/Services/OfficialEvaluationSummaryHtmlRenderer.php');self::assertStringNotContainsString('hr_justification',$h);self::assertStringNotContainsString('deviation_reason',$h);}
 public function testSeparateOfficialStrategiesRemainInUse():void{$s=$this->source('app/Services/PersonnelEvaluationSummaryService.php');self::assertStringContainsString('FacultyEvaluationSummaryStrategy',$s);self::assertStringContainsString('NonTeachingFacultyEvaluationSummaryStrategy',$s);}
 public function testOfflineFieldsRemainBlank():void{$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString("'effectivity'=>null",$s);foreach(['chair','members','president']as$f)self::assertStringContainsString("'$f'",$s);}
 public function testVersionReferenceAndQrArePersisted():void{$m=$this->source('app/Database/Migrations/2026-09-15-000011_CreateOfficialEvaluationDocuments.php');foreach(['evaluation_version','reference_number','qr_payload','summary_payload','superseded_by_document_id']as$f)self::assertStringContainsString($f,$m);$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString('SvgWriter',$s);self::assertStringContainsString("'system_footer'",$s);}
 public function testDocumentIsImmutableAndBoundToOneFinalReview():void{$m=$this->source('app/Database/Migrations/2026-09-15-000011_CreateOfficialEvaluationDocuments.php');self::assertStringContainsString('uq_official_eval_document_review',$m);$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString('$existing=$this->byReview($hrReviewId,false);if($existing)return$existing',$s);self::assertStringNotContainsString("'summary_payload'=>json_encode(\$summary)",substr($s,strpos($s,'foreach($older')));self::assertStringNotContainsString("'reference_number'=>\$reference",substr($s,strpos($s,'foreach($older')));}
 public function testUnauthorizedGenerationAndDownloadDenied():void{$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringContainsString('OFFICIAL_PRINT_ACCESS_DENIED',$s);$c=$this->source('app/Controllers/Api/OfficialEvaluationDocumentController.php');self::assertStringContainsString('public function generate',$c);self::assertStringContainsString('public function download',$c);}
 public function testPresentRankIsNotMutated():void{$s=$this->source('app/Services/OfficialEvaluationDocumentService.php');self::assertStringNotContainsString("table('personnel_profiles')->",$s);}
}
