import React, { useEffect, useMemo, useState } from 'react'
import { AlertCircle, Download, RefreshCw } from 'lucide-react'
import { downloadSignedApprovedRank, loadRankPlacementView, retryRankActivation } from '../../services/rankPlacementViewService'

const rankStatuses = {
  active: ['Current Rank', 'border-emerald-200 bg-emerald-50 text-emerald-800'],
  approved_pending_effectivity: ['Pending Approved Future Rank', 'border-amber-200 bg-amber-50 text-amber-900'],
  historical: ['Historical Rank', 'border-slate-200 bg-slate-50 text-slate-700'],
  cancelled: ['Cancelled Future Rank', 'border-rose-200 bg-rose-50 text-rose-800'],
  corrected: ['Corrected Record', 'border-violet-200 bg-violet-50 text-violet-800'],
  activation_failed: ['Activation Failed', 'border-rose-300 bg-rose-50 text-rose-900']
}
const placementStatuses = {
  current: ['Current Placement', 'border-emerald-200 bg-emerald-50 text-emerald-800'],
  pending_future: ['Pending Future Placement', 'border-amber-200 bg-amber-50 text-amber-900'],
  historical: ['Historical Placement', 'border-slate-200 bg-slate-50 text-slate-700'],
  cancelled: ['Cancelled Placement', 'border-rose-200 bg-rose-50 text-rose-800'],
  corrected: ['Corrected Placement', 'border-violet-200 bg-violet-50 text-violet-800'],
  activation_failed: ['Activation Failed', 'border-rose-300 bg-rose-50 text-rose-900']
}
const rankNotificationTypes = new Set(['approved_rank_recorded','pending_future_rank_created','rank_record_corrected','pending_rank_cancelled','approved_rank_effective','present_rank_changed','approved_rank_activation_delayed'])
const display = value => String(value || 'Not recorded').replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const date = value => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—'

function Status({ value, placement = false }) {
  const [label, style] = (placement ? placementStatuses : rankStatuses)[value] || [display(value), 'border-slate-200 bg-white text-slate-700']
  return <span className={`inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-xs font-bold ${style}`}>{label}</span>
}

function LoadingState() {
  return <main className="mx-auto max-w-7xl space-y-5 py-4" aria-busy="true" aria-label="Loading rank and placement information"><div className="h-8 w-72 animate-pulse rounded bg-slate-200"/><div className="h-24 animate-pulse rounded-xl bg-slate-100"/><div className="h-64 animate-pulse rounded-xl bg-slate-100"/></main>
}

function HistoryTable({ rows, type, role, onDownload, onRetry }) {
  const [page, setPage] = useState(1); const pageSize = 8; const pages = Math.max(1, Math.ceil(rows.length / pageSize)); const visible = rows.slice((page - 1) * pageSize, page * pageSize)
  useEffect(() => setPage(1), [rows.length])
  if (!rows.length) return <div className="border-y border-slate-200 px-4 py-10 text-center"><p className="font-bold text-slate-800">No {type === 'rank' ? 'rank' : 'placement'} history yet.</p><p className="mt-1 text-sm text-slate-500">Verified records will appear here when available.</p></div>
  return <>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] table-fixed text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th scope="col" className="w-[28%] px-4 py-3">{type === 'rank' ? 'Rank' : 'Placement'}</th><th scope="col" className="w-[22%] px-4 py-3">Status</th><th scope="col" className="w-[18%] px-4 py-3">Effectivity</th>{role !== 'reviewer' && <th scope="col" className="w-[20%] px-4 py-3">Details</th>}<th scope="col" className="px-4 py-3 text-right">Actions</th></tr></thead>
    <tbody className="divide-y divide-slate-200">{visible.map((row, index) => { const id = row.id || row.record_id || row.approved_rank_record_id || row.placement_id; const reason = row.correction?.reason || row.cancellation_reason || row.correction_reason || row.recovery_reason; return <tr key={id || `${type}-${index}`} className="align-top hover:bg-slate-50/70"><td className="truncate px-4 py-3 font-bold text-slate-900" title={type === 'rank' ? display(row.approved_rank_code || row.rank_code) : (row.qualification_source_label || display(row.qualification_tier_code))}>{type === 'rank' ? display(row.approved_rank_code || row.rank_code) : (row.qualification_source_label || display(row.qualification_tier_code))}</td><td className="px-4 py-3"><Status value={row.status} placement={type === 'placement'}/></td><td className="px-4 py-3 tabular-nums text-slate-700">{date(row.effectivity_date || row.effective_from)}</td>{role !== 'reviewer' && <td className="px-4 py-3"><span className="block max-w-xs truncate text-slate-600" title={reason || ''}>{reason || (row.activation_failure_reason ? 'Administrative intervention required' : '—')}</span></td>}<td className="px-4 py-3 text-right">{type === 'rank' && role !== 'reviewer' && id && <button type="button" onClick={() => onDownload(id)} aria-label={`Download signed document for ${display(row.approved_rank_code || row.rank_code)}`} className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-bold text-emerald-800 hover:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600"><Download className="h-3.5 w-3.5"/>Signed document</button>}{type === 'rank' && role === 'hr' && row.status === 'activation_failed' && <button type="button" onClick={() => onRetry(id)} aria-label="Retry rank activation" className="ml-2 inline-flex items-center gap-1.5 rounded-lg bg-emerald-800 px-2.5 py-1.5 text-xs font-bold text-white hover:bg-emerald-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-600"><RefreshCw className="h-3.5 w-3.5"/>Retry</button>}</td></tr>})}</tbody></table></div>
    {pages > 1 && <nav aria-label={`${type} history pagination`} className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-sm"><p className="text-slate-500">Page {page} of {pages}</p><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage(value => value - 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 font-bold disabled:opacity-40">Previous</button><button type="button" disabled={page === pages} onClick={() => setPage(value => value + 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 font-bold disabled:opacity-40">Next</button></div></nav>}
  </>
}

export default function RankPlacementWorkspace({ role, personnelId }) {
  const [state, setState] = useState({ phase: 'loading', ranks: [], rankCompatibility: {}, placements: [], notifications: [], error: '' })
  const load = () => { setState(current => ({ ...current, phase: 'loading', error: '' })); loadRankPlacementView(role, personnelId).then(data => setState({ phase: 'ready', ...data, error: '' })).catch(error => setState({ phase: 'error', ranks: [], placements: [], notifications: [], error: error?.error?.message || error?.message || 'Rank and placement information could not be loaded.' })) }
  useEffect(load, [role, personnelId])
  const currentRank = useMemo(() => state.ranks.find(row => row.status === 'active' || row.status === 'current'), [state.ranks]); const pendingRank = useMemo(() => state.ranks.find(row => row.status === 'approved_pending_effectivity'), [state.ranks]); const currentPlacement = useMemo(() => state.placements.find(row => row.status === 'current'), [state.placements]); const pendingPlacement = useMemo(() => state.placements.find(row => row.status === 'pending_future'), [state.placements]); const presentRank = currentRank?.approved_rank_code || currentRank?.rank_code || state.rankCompatibility.current_present_rank
  if (state.phase === 'loading') return <LoadingState/>
  if (state.phase === 'error') return <main className="mx-auto max-w-3xl py-10"><div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-rose-900"><AlertCircle className="h-5 w-5"/><h1 className="mt-2 font-black">Rank and placement information unavailable</h1><p className="mt-1 text-sm">{state.error}</p><button type="button" onClick={load} className="mt-4 rounded-lg bg-rose-900 px-3 py-2 text-sm font-bold text-white focus-visible:ring-2 focus-visible:ring-rose-700">Try again</button></div></main>
  const download = async id => { try { await downloadSignedApprovedRank(id) } catch { setState(current => ({ ...current, error: 'The signed approved ranking document could not be downloaded.' })) } }; const retry = async id => { await retryRankActivation(id); load() }
  const notices = state.notifications.filter(item => rankNotificationTypes.has(item.type)).slice(0, 6)
  return <main className="mx-auto max-w-7xl space-y-8 py-4"><header><h1 className="text-2xl font-black tracking-tight text-slate-950">Rank and Placement</h1><p className="mt-1 max-w-2xl text-sm text-slate-600">Review current, pending, and historical personnel ranking records.</p></header>
    {state.error && <p role="alert" className="rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800">{state.error}</p>}
    <section aria-labelledby="current-rank-heading" className="border-y border-slate-200 py-5"><h2 id="current-rank-heading" className="text-base font-black text-slate-950">Current status</h2><dl className="mt-4 grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Current Rank</dt><dd className="mt-1 font-black text-slate-900">{display(presentRank)}</dd>{!state.rankCompatibility.history_initialized && presentRank && <p className="mt-0.5 text-xs text-slate-500">Legacy Present Rank · history not initialized</p>}</div><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Pending Approved Future Rank</dt><dd className="mt-1 font-black text-slate-900">{display(pendingRank?.approved_rank_code || pendingRank?.rank_code)}</dd><p className="mt-0.5 text-xs text-slate-500">Effectivity {date(pendingRank?.effectivity_date)}</p></div><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Current Placement</dt><dd className="mt-1 font-black text-slate-900">{currentPlacement?.qualification_source_label || display(currentPlacement?.qualification_tier_code || 'Unknown / not initialized')}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Pending Placement</dt><dd className="mt-1 font-black text-slate-900">{pendingPlacement?.qualification_source_label || display(pendingPlacement?.qualification_tier_code)}</dd><p className="mt-0.5 text-xs text-slate-500">Effectivity {date(pendingPlacement?.effective_from)}</p></div></dl></section>
    <section aria-labelledby="rank-history-heading" className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="px-4 py-4"><h2 id="rank-history-heading" className="font-black text-slate-950">Rank History</h2><p className="mt-1 text-sm text-slate-500">{role === 'reviewer' ? 'Rank, status, and effectivity only.' : 'Approved rank records and authorized details.'}</p></div><HistoryTable rows={state.ranks} type="rank" role={role} onDownload={download} onRetry={retry}/></section>
    <section aria-labelledby="placement-history-heading" className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="px-4 py-4"><h2 id="placement-history-heading" className="font-black text-slate-950">{role === 'reviewer' ? 'Current and Pending Placement' : 'Rank Placement History'}</h2><p className="mt-1 text-sm text-slate-500">{role === 'reviewer' ? 'Historical and sensitive placement details are not available in this workspace.' : 'Confirmed placement records and their effective periods.'}</p></div><HistoryTable rows={state.placements} type="placement" role={role} onDownload={download} onRetry={retry}/></section>
    {role === 'personnel' && <section aria-labelledby="rank-notifications-heading"><h2 id="rank-notifications-heading" className="font-black text-slate-950">Recent Rank Notifications</h2>{notices.length ? <ul className="mt-3 divide-y divide-slate-200 border-y border-slate-200">{notices.map(item => <li key={item.id} className="py-3"><p className="font-bold text-slate-900">{item.title}</p><p className="mt-0.5 text-sm text-slate-600">{item.message}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No rank-status notifications yet.</p>}</section>}
  </main>
}
