<?php
namespace App\Services;
use CodeIgniter\Database\BaseConnection;use RuntimeException;
class ApprovedRankActivationService
{
 public function __construct(private ?BaseConnection$db=null,private ?OrganizationalAuthorityResolver$authority=null){$this->db??=db_connect();$this->authority??=new OrganizationalAuthorityResolver($this->db);}
 public function activateDue():array{$ids=array_column($this->db->table('personnel_approved_rank_records')->select('id')->where('status','approved_pending_effectivity')->where('effectivity_date <=',date('Y-m-d'))->orderBy('effectivity_date')->get()->getResultArray(),'id');$results=[];foreach($ids as$id)$results[]=$this->attempt($id,'automatic',null);return$results;}
 public function retry(array$actor,string$id):array{$this->assertHr($actor);return$this->attempt($id,'manual_retry',(string)$actor['profile']['id']);}
 public function requestRecovery(array$actor,string$id,string$path,string$reason):array{$this->assertHr($actor);$paths=['correction'=>['status'=>'correction_pending','event'=>'correction_requested'],'cancellation'=>['status'=>'cancellation_pending','event'=>'cancellation_requested']];if(!isset($paths[$path]))throw new RuntimeException('RECOVERY_PATH_INVALID');if(trim($reason)==='')throw new RuntimeException('RECOVERY_REASON_REQUIRED');$status=$paths[$path]['status'];$event=$paths[$path]['event'];$this->db->transBegin();try{$r=$this->lock($id);if($r['status']!=='activation_failed')throw new RuntimeException('RECOVERY_REQUIRES_ACTIVATION_FAILED');$this->db->table('personnel_approved_rank_records')->where('id',$id)->update(['status'=>$status,'recovery_reason'=>trim($reason)]);$this->event($id,$event,(string)$actor['profile']['id'],'authenticated_hr',['reason'=>trim($reason)]);$this->db->transCommit();return['id'=>$id,'status'=>$status];}catch(\Throwable$e){$this->db->transRollback();throw$e;}}
 private function attempt(string$id,string$trigger,?string$actorId):array
 {
  $context=$trigger==='automatic'?'scheduled_system':'authenticated_hr';$attemptNo=0;$record=null;
  $this->db->transBegin();try{$record=$this->lock($id);$allowed=$trigger==='automatic'?'approved_pending_effectivity':'activation_failed';if($record['status']!==$allowed)throw new RuntimeException($trigger==='automatic'?'APPROVED_RANK_NOT_PENDING':'RETRY_REQUIRES_ACTIVATION_FAILED');if($record['effectivity_date']>date('Y-m-d'))throw new RuntimeException('APPROVED_RANK_NOT_DUE');$attemptNo=$this->nextAttempt($id);$this->activateLocked($record);$now=date('Y-m-d H:i:s');$this->db->table('personnel_approved_rank_records')->where('id',$id)->update(['status'=>'active','activated_at'=>$now,'last_activation_attempt_at'=>$now,'activation_failure_code'=>null,'activation_failure_reason'=>null]);$this->attemptEvent($id,$attemptNo,$trigger,$context,$actorId,'succeeded',null,null,$now);$this->event($id,$trigger==='automatic'?'activation_succeeded':'retry_succeeded',$actorId,$context,['attempt_number'=>$attemptNo,'effectivity_date'=>$record['effectivity_date']]);$this->db->transCommit();$this->notifySuccess($record,$actorId);return['id'=>$id,'status'=>'active','outcome'=>'succeeded','attempt_number'=>$attemptNo];}catch(\Throwable$e){$this->db->transRollback();if($trigger==='automatic'&&$e->getMessage()==='APPROVED_RANK_NOT_PENDING')return['id'=>$id,'status'=>$record['status']??'unknown','outcome'=>'skipped'];if($record&&in_array($record['status'],['approved_pending_effectivity','activation_failed'],true)){$persisted=$this->persistFailure($record,$trigger,$context,$actorId,$attemptNo?:$this->nextAttemptUnlocked($id),$e);if($persisted)$this->notifyFailure($record,$e->getMessage());return['id'=>$id,'status'=>$persisted?'activation_failed':$record['status'],'outcome'=>'failed','failure_code'=>$e->getMessage(),'failure_state_persisted'=>$persisted];}throw$e;}
 }
 private function activateLocked(array$r):void{$person=$this->db->query('SELECT * FROM personnel_profiles WHERE profile_id = ? FOR UPDATE',[$r['personnel_profile_id']])->getRowArray();if(!$person)throw new RuntimeException('PERSONNEL_NOT_FOUND');$present=$this->rank((string)($person['current_rank_title']??''));if($present['rank_code']!==$r['previous_rank_code_snapshot'])throw new RuntimeException('PRESENT_RANK_CONTEXT_CHANGED');$target=$this->db->table('faculty_rank_catalog')->where(['rank_code'=>$r['approved_rank_code'],'is_active'=>1])->get()->getRowArray();if(!$target)throw new RuntimeException('APPROVED_RANK_NOT_SYSTEM_VALID');$pending=$this->db->table('personnel_rank_history')->where(['approved_rank_record_id'=>$r['id'],'status'=>'pending'])->get()->getRowArray();if(!$pending||$pending['effective_from']!==$r['effectivity_date'])throw new RuntimeException('PENDING_RANK_HISTORY_MISMATCH');$current=$this->db->query("SELECT * FROM personnel_rank_history WHERE personnel_profile_id = ? AND status = 'current' FOR UPDATE",[$r['personnel_profile_id']])->getResultArray();if(count($current)>1)throw new RuntimeException('CONFLICTING_CURRENT_RANK_HISTORY');if($current&&$current[0]['effective_from']>=$r['effectivity_date'])throw new RuntimeException('RANK_EFFECTIVE_PERIOD_OVERLAP');if($current)$this->db->table('personnel_rank_history')->where('id',$current[0]['id'])->update(['status'=>'historical','effective_to'=>date('Y-m-d',strtotime($r['effectivity_date'].' -1 day'))]);$this->db->table('personnel_rank_history')->where('id',$pending['id'])->update(['status'=>'current']);$this->db->table('personnel_profiles')->where('profile_id',$r['personnel_profile_id'])->update(['current_rank_title'=>$target['display_label'],'updated_at'=>date('Y-m-d H:i:s')]);}
 private function persistFailure(array$r,string$trigger,string$context,?string$actor,int$n,\Throwable$e):bool{try{$now=date('Y-m-d H:i:s');$this->db->transBegin();$locked=$this->lock($r['id']);if(!in_array($locked['status'],['approved_pending_effectivity','activation_failed'],true)){$this->db->transRollback();return false;}$this->db->table('personnel_approved_rank_records')->where('id',$r['id'])->update(['status'=>'activation_failed','last_activation_attempt_at'=>$now,'activation_failure_code'=>substr($e->getMessage(),0,100),'activation_failure_reason'=>$e->getMessage()]);$this->attemptEvent($r['id'],$n,$trigger,$context,$actor,'failed',substr($e->getMessage(),0,100),$e->getMessage(),$now);$this->event($r['id'],'activation_failed',$actor,$context,['attempt_number'=>$n,'failure_code'=>$e->getMessage()]);$this->db->transCommit();return true;}catch(\Throwable$failure){$this->db->transRollback();log_message('critical','RANK_ACTIVATION_FAILURE_STATE_NOT_PERSISTED '.$r['id'].' '.$failure->getMessage());return false;}}
 private function notifySuccess(array$r,?string$actor):void{$rank=$this->rank($r['approved_rank_code']);$recipients=[[$r['personnel_profile_id'],'approved_rank_effective','Approved rank now effective','Your approved rank '.$rank['display_label'].' is now your Present Rank.']];try{$track=$this->db->table('personnel_evaluation_periods')->where('id',$r['ranking_track_id'])->get()->getRowArray();$a=$this->authority->resolveResponsibleAuthority($r['personnel_profile_id'],$track);if(in_array($a['authority_type'],['DEAN','DEPARTMENT_HEAD'],true))$recipients[]=[$a['authority_profile_id'],'approved_rank_effective_scope','Approved rank now effective',$rank['display_label'].' is now effective for the personnel member.'];}catch(\Throwable){}foreach($this->hrIds()as$hr)$recipients[]=[$hr,'approved_rank_activation_succeeded','Automatic rank activation succeeded',$rank['display_label'].' became effective as scheduled.'];$this->send($r['id'],$actor,$recipients);}
 private function notifyFailure(array$r,string$code):void{$recipients=[[$r['personnel_profile_id'],'approved_rank_activation_delayed','Rank activation delayed','Your scheduled rank change could not be completed automatically. HR has been notified and will review it.']];foreach($this->hrIds()as$hr)$recipients[]=[$hr,'approved_rank_activation_failed','Rank activation requires intervention','Automatic activation failed with code '.$code.'. Retry or select a formal recovery path.'];$this->send($r['id'],null,$recipients);}
 private function send(string$id,?string$actor,array$recipients):void{if(!$this->db->tableExists('notifications'))return;foreach($recipients as[$to,$type,$title,$message])try{$this->db->table('notifications')->insert(['id'=>$this->uuid(),'recipient_profile_id'=>$to,'actor_profile_id'=>$actor,'notification_type'=>$type,'title'=>$title,'message'=>$message,'reference_type'=>'personnel_approved_rank_records','reference_id'=>$id,'is_mandatory'=>1,'created_at'=>date('Y-m-d H:i:s')]);}catch(\Throwable$e){log_message('error','RANK_ACTIVATION_NOTIFICATION_FAILED '.$id.' '.$e->getMessage());}}
 private function hrIds():array{return array_values(array_unique(array_column($this->db->table('profiles p')->select('p.id')->join('profile_roles pr','pr.profile_id=p.id')->join('roles r','r.id=pr.role_id')->where('pr.is_active',1)->whereIn('r.role_key',['hr_staff','hr_admin'])->where('p.status','active')->get()->getResultArray(),'id')));}
 private function lock(string$id):array{$r=$this->db->query('SELECT * FROM personnel_approved_rank_records WHERE id = ? FOR UPDATE',[$id])->getRowArray();if(!$r)throw new RuntimeException('APPROVED_RANK_RECORD_NOT_FOUND');return$r;}private function nextAttempt(string$id):int{$n=$this->db->query('SELECT COALESCE(MAX(attempt_number),0)+1 n FROM personnel_rank_activation_attempts WHERE approved_rank_record_id = ?',[$id])->getRowArray();return(int)$n['n'];}private function nextAttemptUnlocked(string$id):int{return(int)($this->db->table('personnel_rank_activation_attempts')->selectMax('attempt_number','n')->where('approved_rank_record_id',$id)->get()->getRowArray()['n']??0)+1;}
 private function attemptEvent(string$id,int$n,string$trigger,string$context,?string$actor,string$outcome,?string$code,?string$reason,string$at):void{$this->db->table('personnel_rank_activation_attempts')->insert(['id'=>$this->uuid(),'approved_rank_record_id'=>$id,'attempt_number'=>$n,'trigger_type'=>$trigger,'actor_context'=>$context,'performed_by_profile_id'=>$actor,'outcome'=>$outcome,'failure_code'=>$code,'failure_reason'=>$reason,'attempted_at'=>$at]);}private function event(string$id,string$type,?string$actor,string$context,array$p):void{$this->db->table('personnel_approved_rank_events')->insert(['id'=>$this->uuid(),'approved_rank_record_id'=>$id,'event_type'=>$type,'performed_by_profile_id'=>$actor,'actor_context'=>$context,'event_payload'=>json_encode($p)]);}
 private function rank(string$text):array{$r=$this->db->table('faculty_rank_catalog')->where('is_active',1)->groupStart()->where('rank_code',$text)->orWhere('display_label',$text)->groupEnd()->get()->getRowArray();if(!$r)throw new RuntimeException('PRESENT_RANK_UNRESOLVED');return$r;}private function assertHr(array$a):void{$roles=$a['roles']??[$a['role']??''];if(!array_intersect(['hr_staff','hr_admin'],$roles))throw new RuntimeException('APPROVED_RANK_HR_ONLY');}private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
