<?php
namespace App\Services;
use CodeIgniter\Database\BaseConnection;
use InvalidArgumentException;
use RuntimeException;

/** Phase O HR review and decision-only reconsideration versioning. */
class HrFinalRankReviewService
{
 public function __construct(private ?BaseConnection $db=null,private ?RecommendedRankService $recommended=null,private ?OrganizationalAuthorityResolver $authority=null){$this->db??=db_connect();$this->recommended??=new RecommendedRankService($this->db);$this->authority??=new OrganizationalAuthorityResolver($this->db);}
 public function finalize(array $actor,string $recommendedId,string $rankCode,?string $reason):array
 {
  $this->assertHr($actor);$this->assertUnreviewed($recommendedId);$fresh=$this->recommended->assertFreshConfirmedDecision($recommendedId);$d=$fresh['decision'];$c=$fresh['context'];$this->assertLatestReady($c['evaluation']);
  $rankCode=trim($rankCode);$options=array_column($d['valid_rank_options'],'rank_code');if($rankCode===''||!in_array($rankCode,$options,true))throw new InvalidArgumentException('INVALID_HR_FINAL_RANK_OPTION');
  $adjusted=$rankCode!==$d['confirmed_rank_code'];if($adjusted&&trim((string)$reason)==='')throw new InvalidArgumentException('HR_ADJUSTMENT_JUSTIFICATION_REQUIRED');
  $id=$this->uuid();$actorId=(string)$actor['profile']['id'];$now=date('Y-m-d H:i:s');$action=$adjusted?'adjusted':'accepted';
  $this->db->transStart();$this->db->table('personnel_hr_final_rank_reviews')->insert(['id'=>$id,'recommended_rank_decision_id'=>$recommendedId,'personnel_profile_id'=>$d['personnel_profile_id'],'ranking_cycle_id'=>$d['ranking_cycle_id'],'ranking_track_id'=>$d['ranking_track_id'],'evaluation_id'=>$d['evaluation_id'],'evaluation_version'=>$d['evaluation_version'],'evaluator_recommended_rank_code'=>$d['confirmed_rank_code'],'hr_final_rank_code'=>$rankCode,'action_type'=>$action,'hr_justification'=>$adjusted?trim((string)$reason):null,'status'=>'finalized_ready_for_printing','reviewed_by_profile_id'=>$actorId,'reviewed_at'=>$now]);$this->ensureCompletedResultReport($actor,$c['evaluation'],$now);$this->db->table('personnel_evaluations')->where('id',$d['evaluation_id'])->update(['status'=>'completed','finalized_at'=>$now,'updated_at'=>$now]);$this->event($id,$d['evaluation_id'],$action,$actorId,['evaluator_recommendation'=>$d['confirmed_rank_code'],'hr_final_recommendation'=>$rankCode,'justification'=>$adjusted?trim((string)$reason):null,'final_state'=>'Finalized — Ready for Printing']);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('HR_FINAL_RANK_REVIEW_FAILED');return$this->review($id);
 }
 public function returnForReconsideration(array $actor,string $recommendedId,string $reason):array
 {
  $this->assertHr($actor);if(trim($reason)==='')throw new InvalidArgumentException('RECONSIDERATION_REASON_REQUIRED');$this->assertUnreviewed($recommendedId);$fresh=$this->recommended->assertFreshConfirmedDecision($recommendedId);$d=$fresh['decision'];$this->assertLatestReady($fresh['context']['evaluation']);$id=$this->uuid();$actorId=(string)$actor['profile']['id'];$now=date('Y-m-d H:i:s');$this->db->transStart();$this->db->table('personnel_hr_final_rank_reviews')->insert(['id'=>$id,'recommended_rank_decision_id'=>$recommendedId,'personnel_profile_id'=>$d['personnel_profile_id'],'ranking_cycle_id'=>$d['ranking_cycle_id'],'ranking_track_id'=>$d['ranking_track_id'],'evaluation_id'=>$d['evaluation_id'],'evaluation_version'=>$d['evaluation_version'],'evaluator_recommended_rank_code'=>$d['confirmed_rank_code'],'action_type'=>'returned_for_reconsideration','return_reason'=>trim($reason),'status'=>'returned_for_reconsideration','reviewed_by_profile_id'=>$actorId,'reviewed_at'=>$now]);$this->event($id,$d['evaluation_id'],'returned_for_reconsideration',$actorId,['reason'=>trim($reason),'portfolio_revision'=>false]);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('HR_RECONSIDERATION_RETURN_FAILED');return$this->review($id);
 }
 public function beginReconsideration(array $actor,string $reviewId):array
 {
  $review=$this->review($reviewId);if($review['status']!=='returned_for_reconsideration')throw new RuntimeException('RECONSIDERATION_NOT_AVAILABLE');$old=$this->db->table('personnel_evaluations')->where('id',$review['evaluation_id'])->get()->getRowArray();$track=$this->db->table('personnel_evaluation_periods')->where('id',$review['ranking_track_id'])->get()->getRowArray();$resolved=$this->authority->resolveResponsibleAuthority($review['personnel_profile_id'],$track);$actorId=(string)($actor['profile']['id']??'');if(!$this->authority->actorMayAct($resolved,$actorId))throw new RuntimeException('REVIEWER_OUTSIDE_AUTHORIZED_SCOPE');$latest=$this->latest($old);if($latest['id']!==$old['id'])throw new RuntimeException('EVALUATION_VERSION_SUPERSEDED');
  $newId=$this->uuid();$new=$old;unset($new['id']);$new['id']=$newId;$new['version_number']=(int)$old['version_number']+1;$new['previous_version_id']=$old['id'];$new['status']='in_evaluation';$new['finalized_at']=null;$new['final_snapshot']=null;$new['returned_at']=null;$new['return_reason']=null;$new['updated_at']=date('Y-m-d H:i:s');$new['created_at']=date('Y-m-d H:i:s');
  $items=$this->db->table('personnel_evaluation_items')->where('evaluation_id',$old['id'])->get()->getResultArray();$this->db->transStart();$this->db->table('personnel_evaluations')->insert($new);foreach($items as$item){unset($item['id']);$item['id']=$this->uuid();$item['evaluation_id']=$newId;$item['created_at']=date('Y-m-d H:i:s');$item['updated_at']=date('Y-m-d H:i:s');$this->db->table('personnel_evaluation_items')->insert($item);}$this->db->table('personnel_hr_final_rank_reviews')->where('id',$reviewId)->update(['status'=>'reconsideration_started','reconsideration_evaluation_id'=>$newId]);$this->event($reviewId,$newId,'reconsideration_version_created',$actorId,['previous_evaluation_id'=>$old['id'],'previous_version'=>$old['version_number'],'new_version'=>$new['version_number'],'fresh_recommendation_required'=>true]);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('RECONSIDERATION_VERSION_CREATION_FAILED');return['hr_review_id'=>$reviewId,'previous_evaluation_id'=>$old['id'],'evaluation_id'=>$newId,'version_number'=>$new['version_number'],'status'=>'in_evaluation','fresh_recommended_rank_required'=>true];
 }
 public function context(array $actor,string $evaluationId):array
 {
  $evaluation=$this->db->table('personnel_evaluations pe')->select('pe.*,p.full_name,p.institutional_id,pp.personnel_group,pp.current_rank_title')->join('profiles p','p.id=pe.personnel_profile_id')->join('personnel_profiles pp','pp.profile_id=pe.personnel_profile_id')->where('pe.id',$evaluationId)->get()->getRowArray();
  if(!$evaluation)throw new InvalidArgumentException('EVALUATION_NOT_FOUND');
  if(strtoupper((string)$evaluation['personnel_group'])!=='FACULTY')throw new RuntimeException('FACULTY_PHASE_O_NOT_APPLICABLE');
  $latest=$this->latest($evaluation);if($latest['id']!==$evaluation['id'])throw new RuntimeException('EVALUATION_VERSION_SUPERSEDED');
  $actorId=(string)($actor['profile']['id']??'');$roles=$actor['roles']??[];$isHr=(bool)array_intersect(['hr_staff','hr_admin'],$roles);
  if(!$isHr&&$actorId!==(string)$evaluation['evaluator_profile_id'])throw new RuntimeException('PHASE_O_CONTEXT_ACCESS_DENIED');
  $applied=$this->db->table('personnel_rank_applied_for_decisions')->where(['personnel_profile_id'=>$evaluation['personnel_profile_id'],'ranking_track_id'=>$evaluation['evaluation_period_id']])->orderBy('created_at','DESC')->get()->getRowArray();
  $recommended=$this->db->table('personnel_recommended_rank_decisions')->where('evaluation_id',$evaluationId)->orderBy('created_at','DESC')->get()->getRowArray();
  $review=$recommended?$this->db->table('personnel_hr_final_rank_reviews')->where('recommended_rank_decision_id',$recommended['id'])->get()->getRowArray():null;
  $document=$review?$this->db->table('personnel_official_evaluation_documents')->where('hr_final_rank_review_id',$review['id'])->get()->getRowArray():null;
  foreach([&$applied,&$recommended]as&$decision)if($decision&&is_string($decision['valid_rank_options']??null))$decision['valid_rank_options']=json_decode($decision['valid_rank_options'],true)?:[];
  $track=$this->db->table('personnel_evaluation_periods')->select('ranking_cycle_id')->where('id',$evaluation['evaluation_period_id'])->get()->getRowArray();
  return['evaluation'=>['id'=>$evaluation['id'],'version_number'=>(int)$evaluation['version_number'],'status'=>$evaluation['status'],'personnel_profile_id'=>$evaluation['personnel_profile_id'],'ranking_track_id'=>$evaluation['evaluation_period_id'],'ranking_cycle_id'=>$track['ranking_cycle_id']??null,'faculty_name'=>$evaluation['full_name'],'institutional_id'=>$evaluation['institutional_id'],'current_rank_title'=>$evaluation['current_rank_title'],'total_score'=>$evaluation['total_score']??null],'rank_applied_for'=>$applied,'recommended_rank'=>$recommended,'hr_review'=>$review,'official_document'=>$document,'actor_mode'=>$isHr?'hr':'reviewer'];
 }
 private function assertLatestReady(array $e):void{$latest=$this->latest($e);if($latest['id']!==$e['id'])throw new RuntimeException('EVALUATION_VERSION_SUPERSEDED');if($e['status']!=='ready_for_finalization')throw new RuntimeException('EVALUATION_NOT_READY_FOR_HR_FINALIZATION');}
 private function latest(array $e):array{$q=$this->db->table('personnel_evaluations');if(!empty($e['evaluation_root_id']))$q->where('evaluation_root_id',$e['evaluation_root_id']);else$q->where(['personnel_profile_id'=>$e['personnel_profile_id'],'evaluation_period_id'=>$e['evaluation_period_id']]);return$q->orderBy('version_number','DESC')->get()->getRowArray();}
 private function assertHr(array $a):void{if(!array_intersect(['hr_staff','hr_admin'],$a['roles']??[]))throw new RuntimeException('HR_AUTHORITY_REQUIRED');}
 private function assertUnreviewed(string $recommendedId):void{if($this->db->table('personnel_hr_final_rank_reviews')->where('recommended_rank_decision_id',$recommendedId)->countAllResults()>0)throw new RuntimeException('HR_FINAL_RANK_REVIEW_ALREADY_RECORDED');}
 private function ensureCompletedResultReport(array $actor,array $evaluation,string $now):void
 {
  if($this->db->table('personnel_evaluation_reports')->where('evaluation_id',$evaluation['id'])->countAllResults()>0)return;
  $items=$this->db->table('personnel_evaluation_items')->where('evaluation_id',$evaluation['id'])->orderBy('submission_order','ASC')->orderBy('created_at','ASC')->get()->getResultArray();
  $criteria=is_string($evaluation['criteria_snapshot']??null)?json_decode($evaluation['criteria_snapshot'],true):($evaluation['criteria_snapshot']??[]);$criteria=is_array($criteria)?$criteria:[];
  $totals=['areaA_score'=>(float)($evaluation['area_a_score']??0),'areaB_score'=>(float)($evaluation['area_b_score']??0),'areaC_score'=>(float)($evaluation['area_c_score']??0),'total_score'=>(float)($evaluation['total_score']??0)];
  $person=$this->db->table('profiles')->select('id,full_name,institutional_id')->where('id',$evaluation['personnel_profile_id'])->get()->getRowArray()??[];
  $snapshot=['evaluation_id'=>$evaluation['id'],'evaluation_version'=>(int)($evaluation['version_number']??1),'personnel'=>$person,'assignment'=>['college'=>$evaluation['college_name_snapshot']??null,'department'=>$evaluation['department_name_snapshot']??null,'position'=>$evaluation['position_title_snapshot']??null],'evaluation_period'=>['id'=>$evaluation['evaluation_period_id']??null,'name'=>$evaluation['period_name_snapshot']??null,'academic_year'=>$evaluation['academic_year']??null],'criteria_version_id'=>$evaluation['evaluation_scale_version_id']??null,'criteria_snapshot'=>$criteria,'portfolio_version'=>(int)($evaluation['version_number']??1),'evaluator'=>['profile_id'=>$actor['profile']['id'],'full_name'=>$actor['profile']['full_name']??null,'role'=>'HR'],'items'=>$items,'section_totals'=>['A'=>$totals['areaA_score'],'B'=>$totals['areaB_score'],'C'=>$totals['areaC_score']],'grand_total'=>$totals['total_score'],'status'=>'completed','completed_at'=>date(DATE_ATOM,strtotime($now))];
  $snapshot['official_summary']=(new PersonnelEvaluationSummaryService())->build($evaluation,$items,$criteria,$totals);$passing=(float)($criteria['version']['passing_score']??$criteria['sheet']['passing_score']??0);
  $this->db->table('personnel_evaluation_reports')->insert(['id'=>$this->uuid(),'evaluation_id'=>$evaluation['id'],'generated_by'=>$actor['profile']['id'],'report_payload'=>json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'summary_score'=>$totals['total_score'],'passing_status'=>$passing>0&&$totals['total_score']>=$passing?'passed':'not_passed','generated_at'=>$now]);
 }
 private function review(string $id):array{$r=$this->db->table('personnel_hr_final_rank_reviews')->where('id',$id)->get()->getRowArray();if(!$r)throw new InvalidArgumentException('HR_FINAL_RANK_REVIEW_NOT_FOUND');return$r;}
 private function event(string $review,string $evaluation,string $type,string $actor,array $payload):void{$this->db->table('personnel_hr_final_rank_events')->insert(['id'=>$this->uuid(),'hr_review_id'=>$review,'evaluation_id'=>$evaluation,'event_type'=>$type,'performed_by_profile_id'=>$actor,'event_payload'=>json_encode($payload)]);}
 private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
