<?php
namespace App\Services;
use CodeIgniter\Database\BaseConnection;
use InvalidArgumentException;
use RuntimeException;

/** Phase O HR review and decision-only reconsideration versioning. */
class HrFinalRankReviewService
{
 public function __construct(private ?BaseConnection $db=null,private ?RecommendedRankService $recommended=null,private ?OrganizationalAuthorityResolver $authority=null){$this->db??=db_connect();$this->recommended??=new RecommendedRankService($this->db);$this->authority??=new OrganizationalAuthorityResolver($this->db);}
 public function finalize(array $actor,string $recommendedId,string $rankCode,?string $reason):array
 {
  $this->assertHr($actor);$this->assertUnreviewed($recommendedId);$fresh=$this->recommended->assertFreshConfirmedDecision($recommendedId);$d=$fresh['decision'];$c=$fresh['context'];$this->assertLatestReady($c['evaluation']);
  $rankCode=trim($rankCode);$options=array_column($d['valid_rank_options'],'rank_code');if($rankCode===''||!in_array($rankCode,$options,true))throw new InvalidArgumentException('INVALID_HR_FINAL_RANK_OPTION');
  $adjusted=$rankCode!==$d['confirmed_rank_code'];if($adjusted&&trim((string)$reason)==='')throw new InvalidArgumentException('HR_ADJUSTMENT_JUSTIFICATION_REQUIRED');
  $id=$this->uuid();$actorId=(string)$actor['profile']['id'];$now=date('Y-m-d H:i:s');$action=$adjusted?'adjusted':'accepted';
  $this->db->transStart();$this->db->table('personnel_hr_final_rank_reviews')->insert(['id'=>$id,'recommended_rank_decision_id'=>$recommendedId,'personnel_profile_id'=>$d['personnel_profile_id'],'ranking_cycle_id'=>$d['ranking_cycle_id'],'ranking_track_id'=>$d['ranking_track_id'],'evaluation_id'=>$d['evaluation_id'],'evaluation_version'=>$d['evaluation_version'],'evaluator_recommended_rank_code'=>$d['confirmed_rank_code'],'hr_final_rank_code'=>$rankCode,'action_type'=>$action,'hr_justification'=>$adjusted?trim((string)$reason):null,'status'=>'finalized_ready_for_printing','reviewed_by_profile_id'=>$actorId,'reviewed_at'=>$now]);$this->db->table('personnel_evaluations')->where('id',$d['evaluation_id'])->update(['status'=>'completed','finalized_at'=>$now,'updated_at'=>$now]);$this->event($id,$d['evaluation_id'],$action,$actorId,['evaluator_recommendation'=>$d['confirmed_rank_code'],'hr_final_recommendation'=>$rankCode,'justification'=>$adjusted?trim((string)$reason):null,'final_state'=>'Finalized — Ready for Printing']);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('HR_FINAL_RANK_REVIEW_FAILED');return$this->review($id);
 }
 public function returnForReconsideration(array $actor,string $recommendedId,string $reason):array
 {
  $this->assertHr($actor);if(trim($reason)==='')throw new InvalidArgumentException('RECONSIDERATION_REASON_REQUIRED');$this->assertUnreviewed($recommendedId);$fresh=$this->recommended->assertFreshConfirmedDecision($recommendedId);$d=$fresh['decision'];$this->assertLatestReady($fresh['context']['evaluation']);$id=$this->uuid();$actorId=(string)$actor['profile']['id'];$now=date('Y-m-d H:i:s');$this->db->transStart();$this->db->table('personnel_hr_final_rank_reviews')->insert(['id'=>$id,'recommended_rank_decision_id'=>$recommendedId,'personnel_profile_id'=>$d['personnel_profile_id'],'ranking_cycle_id'=>$d['ranking_cycle_id'],'ranking_track_id'=>$d['ranking_track_id'],'evaluation_id'=>$d['evaluation_id'],'evaluation_version'=>$d['evaluation_version'],'evaluator_recommended_rank_code'=>$d['confirmed_rank_code'],'action_type'=>'returned_for_reconsideration','return_reason'=>trim($reason),'status'=>'returned_for_reconsideration','reviewed_by_profile_id'=>$actorId,'reviewed_at'=>$now]);$this->event($id,$d['evaluation_id'],'returned_for_reconsideration',$actorId,['reason'=>trim($reason),'portfolio_revision'=>false]);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('HR_RECONSIDERATION_RETURN_FAILED');return$this->review($id);
 }
 public function beginReconsideration(array $actor,string $reviewId):array
 {
  $review=$this->review($reviewId);if($review['status']!=='returned_for_reconsideration')throw new RuntimeException('RECONSIDERATION_NOT_AVAILABLE');$old=$this->db->table('personnel_evaluations')->where('id',$review['evaluation_id'])->get()->getRowArray();$track=$this->db->table('personnel_evaluation_periods')->where('id',$review['ranking_track_id'])->get()->getRowArray();$resolved=$this->authority->resolveResponsibleAuthority($review['personnel_profile_id'],$track);$actorId=(string)($actor['profile']['id']??'');if(!$this->authority->actorMayAct($resolved,$actorId))throw new RuntimeException('REVIEWER_OUTSIDE_AUTHORIZED_SCOPE');$latest=$this->latest($old);if($latest['id']!==$old['id'])throw new RuntimeException('EVALUATION_VERSION_SUPERSEDED');
  $newId=$this->uuid();$new=$old;unset($new['id']);$new['id']=$newId;$new['version_number']=(int)$old['version_number']+1;$new['previous_version_id']=$old['id'];$new['status']='in_evaluation';$new['finalized_at']=null;$new['final_snapshot']=null;$new['ready_at']=null;$new['returned_at']=null;$new['return_reason']=null;$new['updated_at']=date('Y-m-d H:i:s');$new['created_at']=date('Y-m-d H:i:s');
  $items=$this->db->table('personnel_evaluation_items')->where('evaluation_id',$old['id'])->get()->getResultArray();$this->db->transStart();$this->db->table('personnel_evaluations')->insert($new);foreach($items as$item){unset($item['id']);$item['id']=$this->uuid();$item['evaluation_id']=$newId;$item['created_at']=date('Y-m-d H:i:s');$item['updated_at']=date('Y-m-d H:i:s');$this->db->table('personnel_evaluation_items')->insert($item);}$this->db->table('personnel_hr_final_rank_reviews')->where('id',$reviewId)->update(['status'=>'reconsideration_started','reconsideration_evaluation_id'=>$newId]);$this->event($reviewId,$newId,'reconsideration_version_created',$actorId,['previous_evaluation_id'=>$old['id'],'previous_version'=>$old['version_number'],'new_version'=>$new['version_number'],'fresh_recommendation_required'=>true]);$this->db->transComplete();if(!$this->db->transStatus())throw new RuntimeException('RECONSIDERATION_VERSION_CREATION_FAILED');return['hr_review_id'=>$reviewId,'previous_evaluation_id'=>$old['id'],'evaluation_id'=>$newId,'version_number'=>$new['version_number'],'status'=>'in_evaluation','fresh_recommended_rank_required'=>true];
 }
 private function assertLatestReady(array $e):void{$latest=$this->latest($e);if($latest['id']!==$e['id'])throw new RuntimeException('EVALUATION_VERSION_SUPERSEDED');if($e['status']!=='ready_for_finalization')throw new RuntimeException('EVALUATION_NOT_READY_FOR_HR_FINALIZATION');}
 private function latest(array $e):array{$q=$this->db->table('personnel_evaluations');if(!empty($e['evaluation_root_id']))$q->where('evaluation_root_id',$e['evaluation_root_id']);else$q->where(['personnel_profile_id'=>$e['personnel_profile_id'],'evaluation_period_id'=>$e['evaluation_period_id']]);return$q->orderBy('version_number','DESC')->get()->getRowArray();}
 private function assertHr(array $a):void{if(!in_array('hr_staff',$a['roles']??[],true))throw new RuntimeException('HR_AUTHORITY_REQUIRED');}
 private function assertUnreviewed(string $recommendedId):void{if($this->db->table('personnel_hr_final_rank_reviews')->where('recommended_rank_decision_id',$recommendedId)->countAllResults()>0)throw new RuntimeException('HR_FINAL_RANK_REVIEW_ALREADY_RECORDED');}
 private function review(string $id):array{$r=$this->db->table('personnel_hr_final_rank_reviews')->where('id',$id)->get()->getRowArray();if(!$r)throw new InvalidArgumentException('HR_FINAL_RANK_REVIEW_NOT_FOUND');return$r;}
 private function event(string $review,string $evaluation,string $type,string $actor,array $payload):void{$this->db->table('personnel_hr_final_rank_events')->insert(['id'=>$this->uuid(),'hr_review_id'=>$review,'evaluation_id'=>$evaluation,'event_type'=>$type,'performed_by_profile_id'=>$actor,'event_payload'=>json_encode($payload)]);}
 private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
