<?php

namespace App\Services;

use RuntimeException;
use ZipArchive;

/**
 * Reads the Non-Teaching Faculty annual-review workbook generated by NtfAnnualReviewTemplateService.
 *
 * Only the DS input cells are trusted. Points, totals, percentages, ratings and averages are always
 * recalculated here from the locked criteria of the ranking track and the active rating scale, so a
 * workbook whose formulas were edited or never recalculated cannot change the result.
 */
class NtfAnnualReviewWorkbookParser extends AnnualReviewWorkbookParser
{
    /**
     * @param array $criteria NtfAnnualReviewTemplateService::criteria()
     * @param array $scale    NtfAnnualReviewSettingsService::active('rating_scale')
     */
    public function parseNtf(string $path, string $filename, array $requiredYears, array $criteria, array $scale): array
    {
        if (strtolower(pathinfo($filename, PATHINFO_EXTENSION)) !== 'xlsx') throw new RuntimeException('INVALID_FILE_TYPE: Only .xlsx annual-review workbooks are accepted.');
        if (! is_file($path) || filesize($path) > self::MAX_BYTES) throw new RuntimeException('INVALID_FILE_SIZE: Workbook is missing or exceeds 10 MB.');
        $mime = (new \finfo(FILEINFO_MIME_TYPE))->file($path);
        if (! in_array($mime, ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip', 'application/octet-stream'], true)) throw new RuntimeException('INVALID_FILE_TYPE: File content is not an XLSX workbook.');
        $zip = new ZipArchive();
        if ($zip->open($path) !== true) throw new RuntimeException('MALFORMED_WORKBOOK: Workbook cannot be opened.');
        try {
            if ($zip->locateName('xl/vbaProject.bin') !== false) throw new RuntimeException('UNSUPPORTED_TEMPLATE: Macro-enabled workbooks are not accepted.');
            $shared = $this->sharedStrings($zip);
            $metaPath = $this->sheetPath($zip, NtfAnnualReviewTemplateService::META_SHEET);
            $sheetPath = $this->sheetPath($zip, NtfAnnualReviewTemplateService::SHEET);
            if (! $sheetPath || ! $metaPath) throw new RuntimeException('UNSUPPORTED_TEMPLATE: This is not the AchieveNest Non-Teaching Faculty annual-review template. Download the NTF template from Annual Reviews and use it.');
            $meta = $this->cells($this->xml($zip, $metaPath), $shared);
            if (trim($meta['A1'] ?? '') !== NtfAnnualReviewTemplateService::MARKER || trim($meta['A2'] ?? '') !== NtfAnnualReviewTemplateService::TEMPLATE_ID) throw new RuntimeException('UNSUPPORTED_TEMPLATE: The workbook template marker is missing or unsupported.');
            if ([trim($meta['A5'] ?? ''), trim($meta['A6'] ?? '')] !== array_values($requiredYears)) throw new RuntimeException('UNSUPPORTED_TEMPLATE: Workbook school years (' . trim($meta['A5'] ?? '?') . ' & ' . trim($meta['A6'] ?? '?') . ') do not match the required years (' . implode(' & ', $requiredYears) . '). Download a new template for this cycle.');

            $cells = $this->cells($this->xml($zip, $sheetPath), $shared);
            if (trim($cells['A5'] ?? '') !== 'Name:') throw new RuntimeException('UNSUPPORTED_TEMPLATE: The Name label was moved or removed.');
            $name = trim($cells['B5'] ?? '');
            if ($name === '') throw new RuntimeException('MISSING_PERSONNEL_NAME: Workbook personnel name is missing.');

            $rows = $this->criterionRows($cells, $criteria['items']);
            $issues = [];
            $perYear = [];
            foreach ([0 => NtfAnnualReviewTemplateService::COL_YEAR1_DS, 1 => NtfAnnualReviewTemplateService::COL_YEAR2_DS] as $index => $col) {
                $values = [];
                foreach ($criteria['items'] as $item) {
                    $raw = trim((string) ($cells[$col . $rows[$item['code']]] ?? ''));
                    if ($raw === '') { $values[$item['code']] = null; continue; }
                    if (! is_numeric($raw)) throw new RuntimeException("INVALID_DS: {$item['code']} DS for SY {$requiredYears[$index]} must be a number from 0 to 100.");
                    $ds = round((float) $raw, 2);
                    if ($ds < 0 || $ds > 100) throw new RuntimeException("INVALID_DS: {$item['code']} DS for SY {$requiredYears[$index]} must be between 0 and 100.");
                    $values[$item['code']] = $ds;
                }
                $filled = count(array_filter($values, fn($v) => $v !== null));
                if ($filled > 0 && $filled < count($values)) throw new RuntimeException("INCOMPLETE_DS: Enter a DS for every Area A item for SY {$requiredYears[$index]}, or leave that school year empty.");
                $perYear[$index] = $filled === 0 ? null : $values;
                if ($filled === 0) $issues[] = "No DS values were entered for SY {$requiredYears[$index]}.";
            }

            $items = []; $totals = [null, null]; $ratings = [null, null]; $passing = [null, null]; $percent = [null, null];
            foreach ($criteria['items'] as $item) {
                $entry = ['code' => $item['code'], 'name' => $item['name'], 'max_points' => $item['max_points'], 'weight' => $item['weight'], 'ds' => [null, null], 'points' => [null, null], 'average_points' => null];
                foreach ([0, 1] as $i) {
                    if ($perYear[$i] === null) continue;
                    $entry['ds'][$i] = $perYear[$i][$item['code']];
                    $entry['points'][$i] = round($entry['ds'][$i] * $item['weight'], 2);
                }
                if ($entry['points'][0] !== null && $entry['points'][1] !== null) $entry['average_points'] = round(($entry['points'][0] + $entry['points'][1]) / 2, 2);
                $items[] = $entry;
            }
            foreach ([0, 1] as $i) {
                if ($perYear[$i] === null) continue;
                $totals[$i] = round(array_sum(array_map(fn($e) => $e['points'][$i], $items)), 2);
                $percent[$i] = round($totals[$i] / $criteria['area_max'] * 100, 2);
                $band = NtfAnnualReviewSettingsService::band($percent[$i], $scale['value']);
                $ratings[$i] = $band['key']; $passing[$i] = (bool) $band['passing'];
            }

            $status = ($ratings[0] && $ratings[1]) ? (($passing[0] && $passing[1]) ? 'passed' : 'not_passed') : 'pending';
            $reason = $status === 'pending' ? 'Both required school years need DS values.' : ($status === 'not_passed' ? 'Two annual reviews are not both passing.' : null);
            $payload = [
                'template_identifier' => NtfAnnualReviewTemplateService::TEMPLATE_ID,
                'criteria_version_id' => $criteria['version_id'],
                'area_max' => $criteria['area_max'],
                'school_years' => array_values($requiredYears),
                'items' => $items,
                'totals' => $totals,
                'percentages' => $percent,
                'ratings' => $ratings,
                'passing' => $passing,
                'average_total' => ($totals[0] !== null && $totals[1] !== null) ? round(array_sum(array_column($items, 'average_points')), 2) : null,
                'rating_scale' => ['version' => $scale['version'], 'bands' => $scale['value']['bands'] ?? [], 'is_provisional' => (bool) ($scale['value']['is_provisional'] ?? true)],
                'workbook_personnel_profile_id' => trim($meta['A7'] ?? '') ?: null,
            ];
            return [
                'template_identifier' => NtfAnnualReviewTemplateService::TEMPLATE_ID,
                'detected_personnel_name' => $name,
                'review_1_school_year' => $requiredYears[0], 'review_1_rating' => $ratings[0],
                'review_2_school_year' => $requiredYears[1], 'review_2_rating' => $ratings[1],
                'two_review_status' => $status, 'two_review_reason' => $reason,
                'validation_status' => 'valid', 'validation_issues' => $issues,
                'area_a_payload' => $payload,
            ];
        } finally {
            $zip->close();
        }
    }

    /** Finds each criterion row by its code in column A, so the layout survives cosmetic edits. */
    private function criterionRows(array $cells, array $items): array
    {
        $rows = [];
        foreach ($cells as $ref => $value) {
            if (! preg_match('/^A(\d+)$/', $ref, $m)) continue;
            foreach ($items as $item) if (preg_match('/^' . preg_quote($item['code'], '/') . '(\s|$)/', trim((string) $value))) $rows[$item['code']] = (int) $m[1];
        }
        foreach ($items as $item) if (! isset($rows[$item['code']])) throw new RuntimeException("UNSUPPORTED_TEMPLATE: The {$item['code']} {$item['name']} row is missing. Download a new template.");
        return $rows;
    }
}
