<?php
namespace App\Services;

class OfficialEvaluationSummaryHtmlRenderer
{
    public function render(array $document,string $qrDataUri):string
    {
        $s=$document['summary_payload'];$faculty=$document['classification']==='FACULTY';$rows=$faculty?$this->facultyRows($s):$this->nonTeachingRows($s);$p=$s['personnel_information']??[];$e=fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');
        return '<!doctype html><html><head><meta charset="utf-8"><title>'.$e($document['reference_number']).'</title><style>@page{size:A4;margin:14mm}body{font:12px Arial;color:#111}.form{border:1px solid #111;padding:18px}h1{text-align:center;font-size:18px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #111;padding:6px}th{background:#eee}.num{text-align:right}.approvals{height:115px;border:1px solid #111;margin-top:16px;padding:8px}.footer{display:flex;align-items:center;justify-content:space-between;margin-top:10px;font-size:9px;color:#444}.footer img{width:72px;height:72px}</style></head><body><main class="form"><h1>'.$e($faculty?'Faculty / Administrators Ranking Scale':'Non-Teaching Faculty Ranking Scale').'</h1><p><b>Personnel:</b> '.$e($p['name']??'').' &nbsp; <b>ID:</b> '.$e($p['personnel_id']??'').'</p><p><b>Present Rank:</b> '.$e($s['present_rank']??'').' &nbsp; <b>Rank Applied For:</b> '.$e($s['rank_applied_for']).' &nbsp; <b>Period Covered:</b> '.$e($s['period_covered']??'').'</p>'.$rows.'<p><b>Total:</b> '.$e(number_format((float)$s['total'],2)).' &nbsp; <b>Passing Score:</b> '.$e(number_format((float)$s['passing_score'],2)).' &nbsp; <b>Recommended Rank:</b> '.$e($s['recommended_rank']).'</p><p><b>Effectivity:</b> ____________________</p><div class="approvals"><b>Offline approval/signatures</b><br><br>Chair: ____________________ &nbsp; Members: ____________________<br><br>Approved / President: ____________________ &nbsp; Date: ____________________</div></main><footer class="footer"><span>Evaluation version '.$e($document['evaluation_version']).' · Generated '.$e($document['generated_at']).'<br>Reference '.$e($document['reference_number']).'</span><img alt="Verification QR code" src="'.$e($qrDataUri).'"></footer></body></html>';
    }
    private function facultyRows(array $s):string{$html='<table><thead><tr><th>Official Area / Documents Submitted</th><th class="num">Points Earned</th></tr></thead><tbody>';foreach($s['sections']??[]as$section){$html.='<tr><th>'.htmlspecialchars($section['title']).'</th><th class="num">'.number_format((float)$section['points_earned'],2).'</th></tr>';foreach($section['items']??[]as$i)$html.='<tr><td>'.htmlspecialchars((string)($i['document']??'')).'</td><td class="num">'.number_format((float)$i['points_earned'],2).'</td></tr>';}$html.='</tbody></table>';return$html;}
    private function nonTeachingRows(array $s):string{$html='<table><thead><tr><th>Performance and Personal Indicators</th><th>Weight</th><th>Percentage</th><th>DS</th><th class="num">Points Earned</th></tr></thead><tbody>';foreach($s['performance_personal_indicators']['items']??[]as$i)$html.='<tr><td>'.htmlspecialchars((string)($i['indicator']??'')).'</td><td>'.htmlspecialchars((string)($i['weight']??'')).'</td><td>'.htmlspecialchars((string)($i['percentage']??'')).'</td><td>'.htmlspecialchars((string)($i['ds']??'')).'</td><td class="num">'.number_format((float)$i['points_earned'],2).'</td></tr>';$html.='<tr><th colspan="4">Service and Leadership</th><th></th></tr>';foreach($s['service_leadership']['items']??[]as$i)$html.='<tr><td colspan="4">'.htmlspecialchars((string)($i['document']??'')).'</td><td class="num">'.number_format((float)$i['points_earned'],2).'</td></tr>';return$html.'</tbody></table>';}
}
