<?php
namespace App\Services;
use CodeIgniter\Database\BaseConnection;use CodeIgniter\HTTP\Files\UploadedFile;use InvalidArgumentException;use RuntimeException;
class OfflineApprovedRankService
{
 public function __construct(private ?BaseConnection $db=null,private ?LocalEvidenceStorageService $storage=null,private ?OrganizationalAuthorityResolver $authority=null){$this->db??=db_connect();$this->storage??=new LocalEvidenceStorageService();$this->authority??=new OrganizationalAuthorityResolver($this->db);}
 public function record(array $actor,string $reviewId,array $input,?UploadedFile $file):array
 {
  $this->assertHr($actor);$existing=$this->db->table('personnel_approved_rank_records')->where('hr_final_rank_review_id',$reviewId)->where('status !=','cancelled')->orderBy('recorded_at','DESC')->get()->getRowArray();if($existing)return$existing;
  foreach(['approved_rank_code'=>'APPROVED_RANK_CODE_REQUIRED','approval_date'=>'APPROVAL_DATE_REQUIRED','effectivity_date'=>'EFFECTIVITY_DATE_REQUIRED','official_document_id'=>'OFFICIAL_DOCUMENT_ID_REQUIRED']as$f=>$error)if(trim((string)($input[$f]??''))==='')throw new InvalidArgumentException($error);if(!$file||!$file->isValid())throw new InvalidArgumentException('SIGNED_APPROVED_DOCUMENT_REQUIRED');
  $today=date('Y-m-d');$approval=$this->date($input['approval_date'],'APPROVAL_DATE_INVALID');$effective=$this->date($input['effectivity_date'],'EFFECTIVITY_DATE_INVALID');if($effective<$today)throw new InvalidArgumentException('PAST_EFFECTIVITY_DATE_NOT_ALLOWED');
  $review=$this->db->table('personnel_hr_final_rank_reviews')->where('id',$reviewId)->get()->getRowArray();if(!$review||$review['status']!=='finalized_ready_for_printing')throw new RuntimeException('CASE_NOT_FINALIZED_READY_FOR_PRINTING');
  $document=$this->db->table('personnel_official_evaluation_documents')->where('id',$input['official_document_id'])->get()->getRowArray();if(!$document||$document['status']!=='current'||$document['hr_final_rank_review_id']!==$reviewId||$document['personnel_profile_id']!==$review['personnel_profile_id']||$document['ranking_cycle_id']!==$review['ranking_cycle_id']||$document['ranking_track_id']!==$review['ranking_track_id']||$document['evaluation_id']!==$review['evaluation_id']||(int)$document['evaluation_version']!==(int)$review['evaluation_version'])throw new RuntimeException('OFFICIAL_DOCUMENT_CONTEXT_MISMATCH');
  $code=trim((string)$input['approved_rank_code']);if($code!==$review['hr_final_rank_code'])throw new InvalidArgumentException('APPROVED_RANK_MUST_MATCH_FINAL_HR_RECOMMENDATION');$rank=$this->db->table('faculty_rank_catalog')->where(['rank_code'=>$code,'is_active'=>1])->get()->getRowArray();if(!$rank)throw new InvalidArgumentException('APPROVED_RANK_NOT_SYSTEM_VALID');
  $person=$this->db->table('personnel_profiles')->where('profile_id',$review['personnel_profile_id'])->get()->getRowArray();if(!$person)throw new RuntimeException('PERSONNEL_NOT_FOUND');$previous=$this->rank((string)($person['current_rank_title']??''));
  if($effective>$today&&$this->db->table('personnel_approved_rank_records')->where(['personnel_profile_id'=>$review['personnel_profile_id'],'status'=>'approved_pending_effectivity'])->countAllResults()>0)throw new RuntimeException('ACTIVE_PENDING_FUTURE_RANK_EXISTS');
  if($this->overlaps($review['personnel_profile_id'],$effective))throw new RuntimeException('RANK_EFFECTIVE_PERIOD_OVERLAP');
  $validation=$this->storage->validateFile($file->getTempName(),$file->getClientName());if(!$validation['success'])throw new InvalidArgumentException($validation['error_code']);$id=$this->uuid();$stored=$this->storage->storeFile($file->getTempName(),'approved-rank',$review['personnel_profile_id'],$id,$validation['extension'],true);$status=$effective>$today?'approved_pending_effectivity':'active';$actorId=(string)$actor['profile']['id'];$now=date('Y-m-d H:i:s');
  $this->db->transStart();$this->db->table('personnel_approved_rank_records')->insert(['id'=>$id,'hr_final_rank_review_id'=>$reviewId,'official_document_id'=>$document['id'],'personnel_profile_id'=>$review['personnel_profile_id'],'ranking_cycle_id'=>$review['ranking_cycle_id'],'ranking_track_id'=>$review['ranking_track_id'],'evaluation_id'=>$review['evaluation_id'],'evaluation_version'=>$review['evaluation_version'],'approved_rank_code'=>$code,'previous_rank_code_snapshot'=>$previous['rank_code'],'approval_date'=>$approval,'effectivity_date'=>$effective,'status'=>$status,'signed_document_storage_path'=>$stored['storage_path'],'signed_document_original_name'=>$file->getClientName(),'signed_document_mime_type'=>$stored['detected_mime_type'],'signed_document_sha256'=>$stored['sha256'],'signed_document_byte_size'=>$stored['byte_size'],'recorded_by_profile_id'=>$actorId,'recorded_at'=>$now,'activated_at'=>$status==='active'?$now:null]);$this->db->table('personnel_rank_history')->insert(['id'=>$this->uuid(),'approved_rank_record_id'=>$id,'personnel_profile_id'=>$review['personnel_profile_id'],'rank_code'=>$code,'effective_from'=>$effective,'status'=>$status==='active'?'current':'pending']);if($status==='active')$this->activateApprovedResult($id,$review['personnel_profile_id'],$rank['display_label'],$effective);$event=$status==='active'?'recorded_and_activated':'recorded_pending_effectivity';$this->event($id,$event,$actorId,['approved_rank_code'=>$code,'approval_date'=>$approval,'effectivity_date'=>$effective]);$this->notify($id,$review,$rank['display_label'],$effective,$actorId,$status);$this->db->transComplete();if(!$this->db->transStatus()){$this->storage->deletePhysicalFile($stored['storage_path']);throw new RuntimeException('APPROVED_RANK_RECORDING_FAILED');}return$this->recordById($id);
 }
 public function get(array $actor,string $id):array{$r=$this->recordById($id);if($this->isHr($actor)||$this->isOwner($actor,$r))return$this->privateRecord($r);if($this->isReviewer($actor,$r))return$this->reviewerRecord($r);throw new RuntimeException('APPROVED_RANK_ACCESS_DENIED');}
 public function document(array $actor,string $id):array{$r=$this->recordById($id);if(!$this->isHr($actor)&&!$this->isOwner($actor,$r))throw new RuntimeException('SIGNED_APPROVED_DOCUMENT_ACCESS_DENIED');$path=$this->storage->resolveAbsolutePath($r['signed_document_storage_path']);if(!$path)throw new RuntimeException('SIGNED_APPROVED_DOCUMENT_MISSING');return['path'=>$path,'mime'=>$r['signed_document_mime_type'],'name'=>$r['signed_document_original_name']];}
 private function activateApprovedResult(string $id,string $personnel,string $label,string $effective):void{$current=$this->db->table('personnel_rank_history')->where(['personnel_profile_id'=>$personnel,'status'=>'current'])->where('approved_rank_record_id !=',$id)->get()->getRowArray();if($current){if($current['effective_from']>=$effective)throw new RuntimeException('RANK_EFFECTIVE_PERIOD_OVERLAP');$this->db->table('personnel_rank_history')->where('id',$current['id'])->update(['status'=>'historical','effective_to'=>date('Y-m-d',strtotime($effective.' -1 day'))]);}$this->db->table('personnel_profiles')->where('profile_id',$personnel)->update(['current_rank_title'=>$label,'updated_at'=>date('Y-m-d H:i:s')]);}
 private function overlaps(string $personnel,string $effective):bool{return$this->db->table('personnel_rank_history')->where('personnel_profile_id',$personnel)->groupStart()->where('effective_to',null)->orWhere('effective_to >=',$effective)->groupEnd()->where('effective_from >',$effective)->countAllResults()>0;}
 private function privateRecord(array$r):array{unset($r['signed_document_storage_path'],$r['signed_document_sha256']);return$r;}private function reviewerRecord(array$r):array{return['approved_rank_record_id'=>$r['id'],'personnel_profile_id'=>$r['personnel_profile_id'],'ranking_cycle_id'=>$r['ranking_cycle_id'],'ranking_track_id'=>$r['ranking_track_id'],'approved_rank_code'=>$r['approved_rank_code'],'approval_date'=>$r['approval_date'],'effectivity_date'=>$r['effectivity_date'],'status'=>$r['status']];}
 private function isReviewer(array$a,array$r):bool{try{$track=$this->db->table('personnel_evaluation_periods')->where('id',$r['ranking_track_id'])->get()->getRowArray();$authority=$this->authority->resolveResponsibleAuthority($r['personnel_profile_id'],$track);return$this->authority->actorMayAct($authority,(string)($a['profile']['id']??''));}catch(\Throwable){return false;}}
 private function notify(string$id,array$r,string$rank,string$date,string$actor,string$status):void{if(!$this->db->tableExists('notifications'))return;$recipients=[[$r['personnel_profile_id'],'approved_rank_recorded','Approved rank recorded','Your approved rank '.$rank.' has been recorded with Effectivity Date '.$date.'.']];if($status==='approved_pending_effectivity')$recipients[]=[$r['personnel_profile_id'],'pending_future_rank_created','Future rank scheduled','Your approved rank '.$rank.' is scheduled to become effective on '.$date.'.'];if($status==='active')$recipients[]=[$r['personnel_profile_id'],'present_rank_changed','Present Rank updated','Your Present Rank is now '.$rank.'.'];try{$track=$this->db->table('personnel_evaluation_periods')->where('id',$r['ranking_track_id'])->get()->getRowArray();$a=$this->authority->resolveResponsibleAuthority($r['personnel_profile_id'],$track);if(in_array($a['authority_type'],['DEAN','DEPARTMENT_HEAD'],true)){$recipients[]=[$a['authority_profile_id'],'approved_rank_recorded_scope','Final approved rank recorded','The final approved rank '.$rank.' was recorded with Effectivity Date '.$date.'.'];if($status==='active')$recipients[]=[$a['authority_profile_id'],'approved_rank_effective_scope','Approved rank now effective',$rank.' is now effective for the personnel member.'];}}catch(\Throwable){}foreach($recipients as[$to,$type,$title,$message])$this->db->table('notifications')->insert(['id'=>$this->uuid(),'recipient_profile_id'=>$to,'actor_profile_id'=>$actor,'notification_type'=>$type,'title'=>$title,'message'=>$message,'reference_type'=>'personnel_approved_rank_records','reference_id'=>$id,'is_mandatory'=>1,'created_at'=>date('Y-m-d H:i:s')]);}
 private function event(string$id,string$type,string$actor,array$p):void{$this->db->table('personnel_approved_rank_events')->insert(['id'=>$this->uuid(),'approved_rank_record_id'=>$id,'event_type'=>$type,'performed_by_profile_id'=>$actor,'event_payload'=>json_encode($p)]);}
 private function rank(string$text):array{$r=$this->db->table('faculty_rank_catalog')->where('is_active',1)->groupStart()->where('rank_code',$text)->orWhere('display_label',$text)->groupEnd()->get()->getRowArray();if(!$r)throw new RuntimeException('PRESENT_RANK_UNRESOLVED');return$r;}
 private function recordById(string$id):array{$r=$this->db->table('personnel_approved_rank_records')->where('id',$id)->get()->getRowArray();if(!$r)throw new InvalidArgumentException('APPROVED_RANK_RECORD_NOT_FOUND');return$r;}private function date(string$v,string$e):string{$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException($e);return$v;}
 private function assertHr(array$a):void{if(!$this->isHr($a))throw new RuntimeException('APPROVED_RANK_HR_ONLY');}private function isHr(array$a):bool{$roles=$a['roles']??[$a['role']??''];return(bool)array_intersect(['hr_staff','hr_admin'],$roles);}private function isOwner(array$a,array$r):bool{return(string)($a['profile']['id']??'')===$r['personnel_profile_id'];}private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
