import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, CheckCircle2, History, Home, LoaderCircle } from 'lucide-react'
import { AchieveNestLogo } from '../../components/brand'
import { verifyOfficialEvaluationDocument } from '../../services/officialEvaluationVerificationService'

export default function PublicEvaluationVerificationPage() {
  const { reference } = useParams();const [record,setRecord]=useState(null);const [loading,setLoading]=useState(true)
  useEffect(()=>{let active=true;setLoading(true);verifyOfficialEvaluationDocument(reference).then(data=>{if(active)setRecord(data)}).catch(()=>{if(active)setRecord({verification_status:'Invalid / Not Found'})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reference])
  const valid=record?.verification_status==='Current / Valid';const superseded=record?.verification_status==='Superseded'
  return <div className="min-h-screen bg-slate-50 p-4 text-slate-800"><header className="mx-auto flex w-full max-w-4xl items-center justify-between py-4"><Link to="/" className="rounded-lg bg-white px-2 py-1"><AchieveNestLogo variant="horizontal" size="compact" /><span className="block text-[10px] font-extrabold uppercase tracking-wider text-emerald-700">Public Verification Portal</span></Link><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold"><Home className="h-4 w-4" />Home</Link></header><main className="mx-auto my-16 w-full max-w-xl rounded-3xl border border-slate-200 bg-white p-7 shadow-xl">{loading?<div className="text-center"><LoaderCircle className="mx-auto h-9 w-9 animate-spin text-emerald-700" /><p className="mt-3 font-bold">Verifying document…</p></div>:<><div className="text-center">{valid?<CheckCircle2 className="mx-auto h-14 w-14 text-emerald-700" />:superseded?<History className="mx-auto h-14 w-14 text-amber-600" />:<AlertTriangle className="mx-auto h-14 w-14 text-red-600" />}<h1 className="mt-3 text-2xl font-black">{record.verification_status}</h1>{superseded&&<p className="mt-2 font-bold text-amber-700">A newer official version exists. This historical copy remains authentic.</p>}</div>{(valid||superseded)?<dl className="mt-6 divide-y rounded-xl border text-sm">{[['System reference',record.system_reference_number],['Personnel name',record.personnel_name],['Ranking cycle',record.ranking_cycle],['Document type',record.document_type],['Generated',record.generated_at],['Evaluation version',record.evaluation_version]].map(([label,value])=><div key={label} className="flex justify-between gap-5 p-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-bold">{value}</dd></div>)}</dl>:<p className="mt-5 text-center text-sm text-slate-600">The reference is invalid or no matching official document was found.</p>}</>}</main></div>
}
