import React, { useState } from 'react'
import { Archive, FileImage, LoaderCircle, ShieldCheck, Type, Upload } from 'lucide-react'
import certificateAssetService from '../../../services/certificateAssetService'

const roleFor = type => ({ BACKGROUND: 'background', BORDER_FRAME: 'border_frame', LOGO: 'logo', SEAL: 'seal', WATERMARK: 'watermark', DECORATIVE_ELEMENT: 'decorative_element', FONT: 'font_body' }[type])
export default function GovernedAssetLibrary({ assets, setAssets, bindings, onSelect }) {
  const [filter, setFilter] = useState('ALL'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [license, setLicense] = useState(false)
  const visible = assets.filter(asset => filter === 'ALL' || asset.asset_type === filter)
  const upload = async event => { const file=event.target.files?.[0]; if(!file)return; const type=filter==='ALL'?'BACKGROUND':filter; setBusy(true);setError('');try{const asset=await certificateAssetService.upload({file,assetType:type,displayName:file.name.replace(/\.[^.]+$/,''),licenseAcknowledged:type!=='FONT'||license,licenseNote:type==='FONT'?'Authorized institutional use':''});setAssets(current=>[...current,asset]);onSelect(roleFor(type),asset.asset_version_id)}catch(next){setError(next?.error?.message||next?.message||'Upload failed.')}finally{setBusy(false);event.target.value=''} }
  const archive = async asset => { setBusy(true);setError('');try{await certificateAssetService.archive(asset.id);setAssets(current=>current.filter(item=>item.id!==asset.id))}catch(next){setError(next?.error?.message||next?.message||'Archive failed.')}finally{setBusy(false)} }
  return <section className="border-b border-slate-200 p-4 dark:border-slate-800" aria-labelledby="governed-assets-title"><div className="flex items-center justify-between gap-3"><div><h2 id="governed-assets-title" className="text-sm font-black">Governed library</h2><p className="mt-1 text-xs text-slate-500">Exact immutable asset versions</p></div>{busy&&<LoaderCircle className="h-4 w-4 animate-spin" />}</div><label className="mt-3 block text-xs font-bold">Type<select value={filter} onChange={event=>setFilter(event.target.value)} className="mt-1.5 min-h-10 w-full border border-slate-300 bg-white px-3 dark:border-slate-700 dark:bg-slate-900">{['ALL','BACKGROUND','BORDER_FRAME','LOGO','SEAL','WATERMARK','DECORATIVE_ELEMENT','FONT'].map(type=><option key={type}>{type}</option>)}</select></label>{filter==='FONT'&&<label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={license} onChange={event=>setLicense(event.target.checked)} />I confirm that NDMU is authorized to use this font.</label>}<label className={`mt-3 flex min-h-10 cursor-pointer items-center justify-center gap-2 border px-3 text-xs font-bold ${filter==='FONT'&&!license?'pointer-events-none opacity-50':''}`}><Upload className="h-4 w-4" />Upload {filter==='ALL'?'background':filter.toLowerCase()}<input className="sr-only" type="file" disabled={busy||filter==='FONT'&&!license} accept={filter==='FONT'?'.ttf,.otf,.woff2':'image/png,image/jpeg'} onChange={upload} /></label>{error&&<p role="alert" className="mt-2 text-xs text-rose-700 dark:text-rose-300">{error}</p>}<div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{visible.map(asset=>{const selected=bindings?.[roleFor(asset.asset_type)]===asset.asset_version_id;return <div key={asset.id} className={`border p-3 ${selected?'border-emerald-700 bg-emerald-50 dark:bg-emerald-950':'border-slate-200 dark:border-slate-700'}`}><button type="button" onClick={()=>onSelect(roleFor(asset.asset_type),asset.asset_version_id)} className="flex w-full items-start gap-2 text-left"><span className="mt-0.5">{asset.asset_type==='FONT'?<Type className="h-4 w-4"/>:<FileImage className="h-4 w-4"/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{asset.display_name}</span><span className="block text-[10px] text-slate-500">v{asset.version_number} · {Math.ceil(asset.file_size/1024)} KB · Used {asset.usage_count}×</span></span>{selected&&<ShieldCheck className="h-4 w-4 text-emerald-700"/>}</button><button type="button" onClick={()=>archive(asset)} className="mt-2 flex items-center gap-1 text-[10px] font-bold text-slate-500 hover:text-rose-700"><Archive className="h-3 w-3"/>Archive</button></div>})}{!visible.length&&<p className="py-4 text-center text-xs text-slate-500">No active governed assets in this category.</p>}</div></section>
}
