<?php
declare(strict_types=1);
namespace Tests\Feature;
use App\Controllers\Api\StudentAchievementLifecycleController;use App\Services\AuthorizationService;use App\Services\CanonicalStudentAchievementDraftService;use App\Services\LocalEvidenceStorageService;use App\Services\StudentEvidenceClamAvScanner;use App\Services\StudentEvidencePaddleOcrService;use CodeIgniter\HTTP\IncomingRequest;use CodeIgniter\HTTP\URI;use CodeIgniter\HTTP\UserAgent;use CodeIgniter\Test\CIUnitTestCase;use Config\App;

#[\PHPUnit\Framework\Attributes\Group('manual-proof')]
final class StudentAchievementLifecycleEndpointTest extends CIUnitTestCase
{
    public static function setUpBeforeClass(): void
    {
        \Tests\Support\ManualProofGate::requireOptIn(false);
        parent::setUpBeforeClass();
    }

 protected $db;private array $students;private LocalEvidenceStorageService $storage;private array $draft;private array $physicalPaths=[];
 protected function setUp():void{parent::setUp();$this->db=db_connect('local_defense');$c=new \Config\Database();$c->default=$c->local_defense;$c->defaultGroup='local_defense';\CodeIgniter\Config\Factories::injectMock('config','Database',$c);$this->students=$this->db->table('profiles')->select('id')->where('account_type','student')->where('status','active')->get(2)->getResultArray();self::assertCount(2,$this->students);$this->storage=new LocalEvidenceStorageService();$this->db->transBegin();$this->draft=(new CanonicalStudentAchievementDraftService($this->db))->create($this->students[0]['id']);}
 protected function tearDown():void{foreach($this->physicalPaths as $path)$this->storage->deletePhysicalFile($path);$this->db->transRollback();parent::tearDown();}
 public function testOtherStudentReceivesNonRevealingLifecycleDenial():void{$response=$this->controller($this->students[1]['id'])->show($this->draft['achievement_record_id']);self::assertSame(422,$response->getStatusCode());self::assertSame('STUDENT_ACHIEVEMENT_NOT_FOUND',json_decode($response->getBody(),true)['error']['code']);}
 public function testPendingEvidenceIsCleanedThenReturnsTransientOcrWithoutPersistence():void{$source=dirname(__DIR__,2).'/writable/ocr-audit/dataset/P01_clean_academic_certificate.jpg';$stored=$this->storage->storeFile($source,'student',$this->students[0]['id'],$this->draft['achievement_record_id'],'jpg');try{$e=$this->uuid();$this->db->table('achievement_evidence')->insert(['id'=>$e,'storage_path'=>$stored['storage_path'],'original_filename'=>'fixture.jpg','mime_type'=>'image/jpeg','detected_mime_type'=>'image/jpeg','byte_size'=>$stored['byte_size'],'sha256'=>$stored['sha256'],'uploaded_by'=>$this->students[0]['id'],'security_status'=>'pending','malware_scanner'=>'pending','status'=>'active']);$this->db->table('achievement_version_evidence')->insert(['record_version_id'=>$this->draft['version']['id'],'evidence_id'=>$e,'association_type'=>'PRIMARY_EVIDENCE','is_primary'=>1,'attached_by'=>$this->students[0]['id']]);$response=$this->controller($this->students[0]['id'],new EndpointOcrFake())->scan($this->draft['achievement_record_id'],$e);self::assertSame(200,$response->getStatusCode(),$response->getBody());$body=json_decode($response->getBody(),true);self::assertSame('clean',$body['data']['scan']['status']);self::assertTrue($body['data']['ocr']['advisory_only']);self::assertSame('clean',$this->db->table('achievement_evidence')->where('id',$e)->get()->getRowArray()['security_status']);self::assertSame(0,$this->db->table('document_processing_runs')->where('target_record_version_id',$this->draft['version']['id'])->countAllResults());self::assertSame(0,$this->db->table('machine_field_proposals')->where('source_evidence_id',$e)->countAllResults());}finally{$this->storage->deletePhysicalFile($stored['storage_path']);}}
 public function testInfectedScanRejectsEvidenceWithoutOcr():void{$e=$this->pendingEvidence();$response=$this->controller($this->students[0]['id'],new EndpointOcrFake(),new LifecycleScannerFake('infected'))->scan($this->draft['achievement_record_id'],$e);self::assertSame(200,$response->getStatusCode(),$response->getBody());$body=json_decode($response->getBody(),true);self::assertSame('infected',$body['data']['scan']['status']);self::assertArrayNotHasKey('ocr',$body['data']);$row=$this->db->table('achievement_evidence')->where('id',$e)->get()->getRowArray();self::assertSame('rejected',$row['security_status']);self::assertSame('rejected',$row['status']);self::assertSame('draft',$this->db->table('achievement_record_versions')->where('id',$this->draft['version']['id'])->get()->getRowArray()['submission_state']);}
 public function testUnavailableScanLeavesEvidencePendingWithoutOcr():void{$e=$this->pendingEvidence();$response=$this->controller($this->students[0]['id'],new EndpointOcrFake(),new LifecycleScannerFake('unavailable'))->scan($this->draft['achievement_record_id'],$e);self::assertSame(200,$response->getStatusCode(),$response->getBody());$body=json_decode($response->getBody(),true);self::assertSame('unavailable',$body['data']['scan']['status']);self::assertArrayNotHasKey('ocr',$body['data']);$row=$this->db->table('achievement_evidence')->where('id',$e)->get()->getRowArray();self::assertSame('pending',$row['security_status']);self::assertSame('active',$row['status']);self::assertSame('draft',$this->db->table('achievement_record_versions')->where('id',$this->draft['version']['id'])->get()->getRowArray()['submission_state']);}
 private function pendingEvidence():string{$source=dirname(__DIR__,2).'/writable/ocr-audit/dataset/P01_clean_academic_certificate.jpg';$stored=$this->storage->storeFile($source,'student',$this->students[0]['id'],$this->draft['achievement_record_id'],'jpg');$this->physicalPaths[]=$stored['storage_path'];$e=$this->uuid();$this->db->table('achievement_evidence')->insert(['id'=>$e,'storage_path'=>$stored['storage_path'],'original_filename'=>'fixture.jpg','mime_type'=>'image/jpeg','detected_mime_type'=>'image/jpeg','byte_size'=>$stored['byte_size'],'sha256'=>$stored['sha256'],'uploaded_by'=>$this->students[0]['id'],'security_status'=>'pending','malware_scanner'=>'pending','status'=>'active']);$this->db->table('achievement_version_evidence')->insert(['record_version_id'=>$this->draft['version']['id'],'evidence_id'=>$e,'association_type'=>'PRIMARY_EVIDENCE','is_primary'=>1,'attached_by'=>$this->students[0]['id']]);return$e;}
 private function controller(string $id,?StudentEvidencePaddleOcrService $ocr=null,?StudentEvidenceClamAvScanner $scanner=null):StudentAchievementLifecycleController{$auth=$this->createMock(AuthorizationService::class);$auth->method('resolveActor')->willReturn(['profile'=>['id'=>$id,'account_type'=>'student']]);$c=new StudentAchievementLifecycleController($auth,new CanonicalStudentAchievementDraftService($this->db),$this->storage,$scanner,$ocr,$this->db);$c->initController($this->request(),service('response'),service('logger'));return$c;}
 private function request():IncomingRequest{$r=new IncomingRequest(new App(),new URI('http://localhost/api/v1/student/achievements/x'),null,new UserAgent());$r->setMethod('POST');$r->setHeader('Authorization','Bearer fixture');return$r;}private function uuid():string{return sprintf('%s-%s-%s-%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),bin2hex(random_bytes(2)),bin2hex(random_bytes(2)),bin2hex(random_bytes(6)));}
}
final class EndpointOcrFake extends StudentEvidencePaddleOcrService{public function extract(string $path,string $mime):array{return['ok'=>true,'engine'=>'paddleocr','advisory_only'=>true,'pages'=>[['page_index'=>1,'raw_text_lines'=>['Evidence text'],'confidence'=>0.9,'boxes'=>[]]],'suggestions'=>[],'warnings'=>[]];}}
final class LifecycleScannerFake extends StudentEvidenceClamAvScanner{public function __construct(private readonly string $status){}public function scan(string $path):array{return['status'=>$this->status,'code'=>'TEST_'.strtoupper($this->status)];}}
