<?php
namespace App\Controllers\Api;
/*
 * PARKED (2026-09-30): student_portfolio_records is the single system of record for student
 * achievements in this release. This canonical lifecycle is retained but no UI calls it.
 * See docs/IMPLEMENTATION_PROMPT_STUDENT_ACHIEVEMENT_WORKFLOW.md (section 0) before reusing it.
 */
use App\Services\AuthorizationService;use App\Services\CanonicalStudentAchievementDraftService;use App\Services\LocalEvidenceStorageService;use App\Services\StudentAchievementEvidenceUploadPolicy;use App\Services\StudentEvidenceClamAvScanner;use App\Services\StudentEvidencePaddleOcrService;use CodeIgniter\API\ResponseTrait;use CodeIgniter\Controller;use CodeIgniter\Database\BaseConnection;use Throwable;
final class StudentAchievementLifecycleController extends Controller{
 use ResponseTrait;public function __construct(private ?AuthorizationService $auth=null,private ?CanonicalStudentAchievementDraftService $drafts=null,private ?LocalEvidenceStorageService $storage=null,private ?StudentEvidenceClamAvScanner $scanner=null,private ?StudentEvidencePaddleOcrService $ocr=null,private ?BaseConnection $database=null){}
 private function actor():?array{$a=($this->auth??=new AuthorizationService())->resolveActor($this->request->getHeaderLine('Authorization'));return $a!==null&&($a['profile']['account_type']??'')==='student'?$a:null;}
 private function service():CanonicalStudentAchievementDraftService{return $this->drafts??=new CanonicalStudentAchievementDraftService();}
 private function database():BaseConnection{return $this->database??=db_connect();}
 public function options():mixed{return $this->respond(null,204);} public function create():mixed{return $this->run(fn($a)=>$this->service()->create($a['profile']['id']),201);} public function show(string $id):mixed{return $this->run(fn($a)=>$this->service()->read($a['profile']['id'],$id),200,false);}
 public function save(string $id):mixed{return $this->run(function($a)use($id){$p=$this->request->getJSON(true)??[];return $this->service()->save($a['profile']['id'],$id,$p['contract_code']??null,is_array($p['fields']??null)?$p['fields']:[]);});}
 public function upload(string $id):mixed{return $this->run(function($a)use($id){$view=$this->service()->read($a['profile']['id'],$id);if(!in_array($view['version']['submission_state'],['draft','revision_requested'],true))throw new \RuntimeException('STUDENT_ACHIEVEMENT_VERSION_NOT_EDITABLE');$f=$this->request->getFile('file');if(!$f||!$f->isValid())throw new \RuntimeException('FILE_REQUIRED');$s=$this->storage??=new LocalEvidenceStorageService();$v=(new StudentAchievementEvidenceUploadPolicy($s))->validate($f->getTempName(),$f->getClientName());if(!($v['success']??false))throw new \RuntimeException($v['error_code']??'STUDENT_EVIDENCE_TYPE_NOT_ALLOWED');$stored=$s->storeFile($f->getTempName(),'student',$a['profile']['id'],$id,$v['extension'],true);$eid=$this->uuid();$this->database()->table('achievement_evidence')->insert(['id'=>$eid,'storage_path'=>$stored['storage_path'],'original_filename'=>$f->getClientName(),'mime_type'=>$v['detected_mime'],'detected_mime_type'=>$v['detected_mime'],'byte_size'=>$stored['byte_size'],'sha256'=>$stored['sha256'],'uploaded_by'=>$a['profile']['id'],'security_status'=>'pending','malware_scanner'=>'clamav_pending','status'=>'active']);$this->database()->table('achievement_version_evidence')->insert(['record_version_id'=>$view['version']['id'],'evidence_id'=>$eid,'association_type'=>'student_supporting_evidence','is_primary'=>1,'attached_by'=>$a['profile']['id']]);return ['evidence_id'=>$eid,'security_status'=>'pending'];},201);}
 public function preview(string $id,string $evidence):mixed{$a=$this->actor();if(!$a)return $this->respond(['error'=>['code'=>'UNAUTHORIZED']],401);try{$row=$this->service()->evidence($a['profile']['id'],$id,$evidence)['evidence'];$mime=(string)($row['detected_mime_type']??$row['mime_type']??'');if(!in_array($mime,['image/jpeg','image/png','application/pdf'],true))throw new \RuntimeException('STUDENT_ACHIEVEMENT_EVIDENCE_TYPE_NOT_PREVIEWABLE');$path=($this->storage??=new LocalEvidenceStorageService())->resolveAbsolutePath((string)$row['storage_path']);if($path===null||!is_file($path))throw new \RuntimeException('STUDENT_ACHIEVEMENT_EVIDENCE_UNAVAILABLE');$name=preg_replace('/[^A-Za-z0-9._-]/','_',basename((string)$row['original_filename']));return $this->response->setHeader('Content-Type',$mime)->setHeader('Content-Disposition','inline; filename="'.$name.'"')->setHeader('Cache-Control','private, no-store')->setBody((string)file_get_contents($path));}catch(Throwable$e){return $this->respond(['error'=>['code'=>$e->getMessage()]],422);}}
 public function remove(string $id,string $evidence):mixed{return $this->run(fn($a)=>$this->service()->detachEvidence($a['profile']['id'],$id,$evidence));}
 public function scan(string $id,string $evidence):mixed{return $this->run(function($a)use($id,$evidence){$v=$this->service()->read($a['profile']['id'],$id);$e=null;foreach($v['evidence'] as $row)if($row['id']===$evidence)$e=$row;if(!$e)throw new \RuntimeException('EVIDENCE_NOT_FOUND');$row=$this->database()->table('achievement_evidence')->where('id',$evidence)->get()->getRowArray();$path=($this->storage??=new LocalEvidenceStorageService())->resolveAbsolutePath($row['storage_path']);$r=($this->scanner??=new StudentEvidenceClamAvScanner())->scan((string)$path);$response=['scan'=>$r];if($r['status']==='clean'){$this->database()->table('achievement_evidence')->where('id',$evidence)->update(['security_status'=>'clean','malware_scanner'=>'clamav_1_5_4','security_validated_at'=>date('Y-m-d H:i:s.u')]);try{$response['ocr']=($this->ocr??=new StudentEvidencePaddleOcrService())->extract((string)$path,(string)$row['detected_mime_type']);}catch(Throwable $x){$response['ocr_error']='OCR assistance was unavailable. You can continue with manual entry.';}}elseif($r['status']==='infected')$this->database()->table('achievement_evidence')->where('id',$evidence)->update(['security_status'=>'rejected','status'=>'rejected','malware_scanner'=>'clamav_1_5_4','security_validated_at'=>date('Y-m-d H:i:s.u')]);return $response;});}
 public function submit(string $id):mixed{return $this->run(fn($a)=>$this->service()->submit($a['profile']['id'],$id));}
 private function run(callable $fn,int $ok=200,bool $write=true):mixed{if($write)return $this->respond(['error'=>['code'=>'CANONICAL_STUDENT_WRITES_DISABLED','message'=>'This student achievement write API is parked. Use the supported portfolio workflow.']],410);$a=$this->actor();if(!$a)return $this->respond(['error'=>['code'=>'UNAUTHORIZED']],401);try{return $this->respond(['data'=>$fn($a)],$ok);}catch(Throwable $e){return $this->respond(['error'=>['code'=>$e->getMessage()]],422);}}
 private function uuid():string{return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',random_int(0,65535),random_int(0,65535),random_int(0,4095)|0x4000,random_int(0,16383)|0x8000,random_int(0,65535),random_int(0,65535),random_int(0,65535),random_int(0,65535));}}
